// Generated by scripts/build-verified-lichess-runtime-corpus.mjs. Do not edit by hand.

export const VERIFIED_FINAL_RUNTIME_VERSION = 'final-v6' as const
export const VERIFIED_FINAL_RUNTIME_PATH = '/data/verified-lichess-tactics-v1/final-v6' as const

export type VerifiedFinalTacticCourse = {
  trainerKey: string
  theme: string
  label: string
  stage: 1 | 2 | 3 | 4
  exerciseCount: number
  chunkCount: number
  learnerDataBasePath: string
}

export const VERIFIED_FINAL_TACTIC_COURSES: readonly VerifiedFinalTacticCourse[] = [
  {
    "trainerKey": "tactic-bishop-fork-m1",
    "theme": "bishop-fork",
    "label": "Bishop Fork",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-fork-m1"
  },
  {
    "trainerKey": "tactic-bishop-fork-m2",
    "theme": "bishop-fork",
    "label": "Bishop Fork",
    "stage": 2,
    "exerciseCount": 37,
    "chunkCount": 2,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-fork-m2"
  },
  {
    "trainerKey": "tactic-bishop-fork-m3",
    "theme": "bishop-fork",
    "label": "Bishop Fork",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-fork-m3"
  },
  {
    "trainerKey": "tactic-bishop-fork-m4",
    "theme": "bishop-fork",
    "label": "Bishop Fork",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-fork-m4"
  },
  {
    "trainerKey": "tactic-bishop-pin-m1",
    "theme": "bishop-pin",
    "label": "Bishop Pin",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-pin-m1"
  },
  {
    "trainerKey": "tactic-bishop-pin-m2",
    "theme": "bishop-pin",
    "label": "Bishop Pin",
    "stage": 2,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-pin-m2"
  },
  {
    "trainerKey": "tactic-bishop-pin-m3",
    "theme": "bishop-pin",
    "label": "Bishop Pin",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-pin-m3"
  },
  {
    "trainerKey": "tactic-bishop-pin-m4",
    "theme": "bishop-pin",
    "label": "Bishop Pin",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-pin-m4"
  },
  {
    "trainerKey": "tactic-bishop-skewer-m1",
    "theme": "bishop-skewer",
    "label": "Bishop Skewer",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-skewer-m1"
  },
  {
    "trainerKey": "tactic-bishop-skewer-m3",
    "theme": "bishop-skewer",
    "label": "Bishop Skewer",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-skewer-m3"
  },
  {
    "trainerKey": "tactic-bishop-skewer-m4",
    "theme": "bishop-skewer",
    "label": "Bishop Skewer",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/bishop-skewer-m4"
  },
  {
    "trainerKey": "tactic-clearance-sacrifice-m2",
    "theme": "clearance-sacrifice",
    "label": "Clearance Sacrifice",
    "stage": 2,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/clearance-sacrifice-m2"
  },
  {
    "trainerKey": "tactic-deflection-m1",
    "theme": "deflection",
    "label": "Deflection",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/deflection-m1"
  },
  {
    "trainerKey": "tactic-diagonal-clearance-m1",
    "theme": "diagonal-clearance",
    "label": "Diagonal Clearance",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/diagonal-clearance-m1"
  },
  {
    "trainerKey": "tactic-diagonal-clearance-m3",
    "theme": "diagonal-clearance",
    "label": "Diagonal Clearance",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/diagonal-clearance-m3"
  },
  {
    "trainerKey": "tactic-diagonal-clearance-m4",
    "theme": "diagonal-clearance",
    "label": "Diagonal Clearance",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/diagonal-clearance-m4"
  },
  {
    "trainerKey": "tactic-discovered-attack-m1",
    "theme": "discovered-attack",
    "label": "Discovered Attack",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/discovered-attack-m1"
  },
  {
    "trainerKey": "tactic-discovered-attack-m3",
    "theme": "discovered-attack",
    "label": "Discovered Attack",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/discovered-attack-m3"
  },
  {
    "trainerKey": "tactic-discovered-attack-m4",
    "theme": "discovered-attack",
    "label": "Discovered Attack",
    "stage": 4,
    "exerciseCount": 76,
    "chunkCount": 4,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/discovered-attack-m4"
  },
  {
    "trainerKey": "tactic-discovered-check-m1",
    "theme": "discovered-check",
    "label": "Discovered Check",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/discovered-check-m1"
  },
  {
    "trainerKey": "tactic-discovered-check-m2",
    "theme": "discovered-check",
    "label": "Discovered Check",
    "stage": 2,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/discovered-check-m2"
  },
  {
    "trainerKey": "tactic-discovered-check-m3",
    "theme": "discovered-check",
    "label": "Discovered Check",
    "stage": 3,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/discovered-check-m3"
  },
  {
    "trainerKey": "tactic-discovered-check-m4",
    "theme": "discovered-check",
    "label": "Discovered Check",
    "stage": 4,
    "exerciseCount": 25,
    "chunkCount": 2,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/discovered-check-m4"
  },
  {
    "trainerKey": "tactic-double-check-m1",
    "theme": "double-check",
    "label": "Double Check",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/double-check-m1"
  },
  {
    "trainerKey": "tactic-en-passant-m1",
    "theme": "en-passant",
    "label": "En Passant",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/en-passant-m1"
  },
  {
    "trainerKey": "tactic-en-passant-m2",
    "theme": "en-passant",
    "label": "En Passant",
    "stage": 2,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/en-passant-m2"
  },
  {
    "trainerKey": "tactic-en-passant-m3",
    "theme": "en-passant",
    "label": "En Passant",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/en-passant-m3"
  },
  {
    "trainerKey": "tactic-en-passant-m4",
    "theme": "en-passant",
    "label": "En Passant",
    "stage": 4,
    "exerciseCount": 77,
    "chunkCount": 4,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/en-passant-m4"
  },
  {
    "trainerKey": "tactic-file-clearance-m1",
    "theme": "file-clearance",
    "label": "File Clearance",
    "stage": 1,
    "exerciseCount": 96,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/file-clearance-m1"
  },
  {
    "trainerKey": "tactic-file-clearance-m2",
    "theme": "file-clearance",
    "label": "File Clearance",
    "stage": 2,
    "exerciseCount": 84,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/file-clearance-m2"
  },
  {
    "trainerKey": "tactic-file-clearance-m3",
    "theme": "file-clearance",
    "label": "File Clearance",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/file-clearance-m3"
  },
  {
    "trainerKey": "tactic-file-clearance-m4",
    "theme": "file-clearance",
    "label": "File Clearance",
    "stage": 4,
    "exerciseCount": 141,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/file-clearance-m4"
  },
  {
    "trainerKey": "tactic-hanging-piece-m1",
    "theme": "hanging-piece",
    "label": "Hanging Piece",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/hanging-piece-m1"
  },
  {
    "trainerKey": "tactic-king-fork-m3",
    "theme": "king-fork",
    "label": "King Fork",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/king-fork-m3"
  },
  {
    "trainerKey": "tactic-king-fork-m4",
    "theme": "king-fork",
    "label": "King Fork",
    "stage": 4,
    "exerciseCount": 29,
    "chunkCount": 2,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/king-fork-m4"
  },
  {
    "trainerKey": "tactic-knight-fork-m1",
    "theme": "knight-fork",
    "label": "Knight Fork",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/knight-fork-m1"
  },
  {
    "trainerKey": "tactic-knight-fork-m2",
    "theme": "knight-fork",
    "label": "Knight Fork",
    "stage": 2,
    "exerciseCount": 83,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/knight-fork-m2"
  },
  {
    "trainerKey": "tactic-knight-fork-m3",
    "theme": "knight-fork",
    "label": "Knight Fork",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/knight-fork-m3"
  },
  {
    "trainerKey": "tactic-knight-fork-m4",
    "theme": "knight-fork",
    "label": "Knight Fork",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/knight-fork-m4"
  },
  {
    "trainerKey": "tactic-knight-underpromotion-m1",
    "theme": "knight-underpromotion",
    "label": "Knight Underpromotion",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/knight-underpromotion-m1"
  },
  {
    "trainerKey": "tactic-knight-underpromotion-m2",
    "theme": "knight-underpromotion",
    "label": "Knight Underpromotion",
    "stage": 2,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/knight-underpromotion-m2"
  },
  {
    "trainerKey": "tactic-pawn-fork-m1",
    "theme": "pawn-fork",
    "label": "Pawn Fork",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/pawn-fork-m1"
  },
  {
    "trainerKey": "tactic-pawn-fork-m3",
    "theme": "pawn-fork",
    "label": "Pawn Fork",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/pawn-fork-m3"
  },
  {
    "trainerKey": "tactic-pawn-fork-m4",
    "theme": "pawn-fork",
    "label": "Pawn Fork",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/pawn-fork-m4"
  },
  {
    "trainerKey": "tactic-promotion-m1",
    "theme": "promotion",
    "label": "Promotion",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/promotion-m1"
  },
  {
    "trainerKey": "tactic-promotion-m2",
    "theme": "promotion",
    "label": "Promotion",
    "stage": 2,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/promotion-m2"
  },
  {
    "trainerKey": "tactic-promotion-m3",
    "theme": "promotion",
    "label": "Promotion",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/promotion-m3"
  },
  {
    "trainerKey": "tactic-promotion-m4",
    "theme": "promotion",
    "label": "Promotion",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/promotion-m4"
  },
  {
    "trainerKey": "tactic-queen-fork-m1",
    "theme": "queen-fork",
    "label": "Queen Fork",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-fork-m1"
  },
  {
    "trainerKey": "tactic-queen-fork-m2",
    "theme": "queen-fork",
    "label": "Queen Fork",
    "stage": 2,
    "exerciseCount": 103,
    "chunkCount": 6,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-fork-m2"
  },
  {
    "trainerKey": "tactic-queen-fork-m3",
    "theme": "queen-fork",
    "label": "Queen Fork",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-fork-m3"
  },
  {
    "trainerKey": "tactic-queen-fork-m4",
    "theme": "queen-fork",
    "label": "Queen Fork",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-fork-m4"
  },
  {
    "trainerKey": "tactic-queen-pin-m1",
    "theme": "queen-pin",
    "label": "Queen Pin",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-pin-m1"
  },
  {
    "trainerKey": "tactic-queen-pin-m2",
    "theme": "queen-pin",
    "label": "Queen Pin",
    "stage": 2,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-pin-m2"
  },
  {
    "trainerKey": "tactic-queen-pin-m3",
    "theme": "queen-pin",
    "label": "Queen Pin",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-pin-m3"
  },
  {
    "trainerKey": "tactic-queen-pin-m4",
    "theme": "queen-pin",
    "label": "Queen Pin",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-pin-m4"
  },
  {
    "trainerKey": "tactic-queen-skewer-m1",
    "theme": "queen-skewer",
    "label": "Queen Skewer",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-skewer-m1"
  },
  {
    "trainerKey": "tactic-queen-skewer-m3",
    "theme": "queen-skewer",
    "label": "Queen Skewer",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-skewer-m3"
  },
  {
    "trainerKey": "tactic-queen-skewer-m4",
    "theme": "queen-skewer",
    "label": "Queen Skewer",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/queen-skewer-m4"
  },
  {
    "trainerKey": "tactic-rank-clearance-m1",
    "theme": "rank-clearance",
    "label": "Rank Clearance",
    "stage": 1,
    "exerciseCount": 61,
    "chunkCount": 4,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rank-clearance-m1"
  },
  {
    "trainerKey": "tactic-rank-clearance-m2",
    "theme": "rank-clearance",
    "label": "Rank Clearance",
    "stage": 2,
    "exerciseCount": 23,
    "chunkCount": 2,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rank-clearance-m2"
  },
  {
    "trainerKey": "tactic-rank-clearance-m3",
    "theme": "rank-clearance",
    "label": "Rank Clearance",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rank-clearance-m3"
  },
  {
    "trainerKey": "tactic-rank-clearance-m4",
    "theme": "rank-clearance",
    "label": "Rank Clearance",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rank-clearance-m4"
  },
  {
    "trainerKey": "tactic-remove-the-defender-m1",
    "theme": "remove-the-defender",
    "label": "Removal of Defender by Capture",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/remove-the-defender-m1"
  },
  {
    "trainerKey": "tactic-rook-fork-m1",
    "theme": "rook-fork",
    "label": "Rook Fork",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-fork-m1"
  },
  {
    "trainerKey": "tactic-rook-fork-m3",
    "theme": "rook-fork",
    "label": "Rook Fork",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-fork-m3"
  },
  {
    "trainerKey": "tactic-rook-fork-m4",
    "theme": "rook-fork",
    "label": "Rook Fork",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-fork-m4"
  },
  {
    "trainerKey": "tactic-rook-pin-m1",
    "theme": "rook-pin",
    "label": "Rook Pin",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-pin-m1"
  },
  {
    "trainerKey": "tactic-rook-pin-m2",
    "theme": "rook-pin",
    "label": "Rook Pin",
    "stage": 2,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-pin-m2"
  },
  {
    "trainerKey": "tactic-rook-pin-m3",
    "theme": "rook-pin",
    "label": "Rook Pin",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-pin-m3"
  },
  {
    "trainerKey": "tactic-rook-pin-m4",
    "theme": "rook-pin",
    "label": "Rook Pin",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-pin-m4"
  },
  {
    "trainerKey": "tactic-rook-skewer-m1",
    "theme": "rook-skewer",
    "label": "Rook Skewer",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-skewer-m1"
  },
  {
    "trainerKey": "tactic-rook-skewer-m3",
    "theme": "rook-skewer",
    "label": "Rook Skewer",
    "stage": 3,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-skewer-m3"
  },
  {
    "trainerKey": "tactic-rook-skewer-m4",
    "theme": "rook-skewer",
    "label": "Rook Skewer",
    "stage": 4,
    "exerciseCount": 160,
    "chunkCount": 8,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/rook-skewer-m4"
  },
  {
    "trainerKey": "tactic-zwischencheck-m1",
    "theme": "zwischencheck",
    "label": "Zwischencheck",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/zwischencheck-m1"
  },
  {
    "trainerKey": "tactic-zwischenzug-m1",
    "theme": "zwischenzug",
    "label": "Capture Zwischenzug",
    "stage": 1,
    "exerciseCount": 100,
    "chunkCount": 5,
    "learnerDataBasePath": "/data/verified-lichess-tactics-v1/final-v6/zwischenzug-m1"
  }
] as const

export const VERIFIED_FINAL_TACTIC_COURSE_BY_TRAINER_KEY = Object.fromEntries(
 VERIFIED_FINAL_TACTIC_COURSES.map((course) => [course.trainerKey, course]),
) as Record<string, VerifiedFinalTacticCourse>

export const VERIFIED_FINAL_TACTIC_UNAVAILABLE = [
  {
    "theme": "bishop-xray",
    "label": "Bishop X-Ray",
    "status": "metadata-only",
    "reason": "No approved runtime corpus is available."
  },
  {
    "theme": "queen-xray",
    "label": "Queen X-Ray",
    "status": "metadata-only",
    "reason": "No approved runtime corpus is available."
  },
  {
    "theme": "rook-xray",
    "label": "Rook X-Ray",
    "status": "metadata-only",
    "reason": "No approved runtime corpus is available."
  },
  {
    "theme": "trapped-piece",
    "label": "Trapped Piece",
    "status": "unavailable",
    "reason": "No approved runtime corpus is available."
  },
  {
    "theme": "overload",
    "label": "Overload",
    "status": "unavailable",
    "reason": "No approved runtime corpus is available."
  },
  {
    "theme": "square-clearance",
    "label": "Square Clearance",
    "status": "unavailable",
    "reason": "Two fail-closed attempts produced no strict TRUE M2 candidates."
  }
] as const
