import { VERIFIED_FINAL_TACTIC_COURSES } from "./generatedFinalVerifiedTaxonomy"

export const patternTacticPageConfigs = {
 defenseM1: {
 title: "Defense - Tactic in 1",
 manifestPath: "/data/pattern-tactics/defense/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/defense/m1",
 progressKey: "tactic-defense-m1",
 trainerKey: "tactic-defense-m1",
 },
 defenseM2: {
 title: "Defense - Tactic in 2",
 manifestPath: "/data/pattern-tactics/defense/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/defense/m2",
 progressKey: "tactic-defense-m2",
 trainerKey: "tactic-defense-m2",
 },
 defenseM3: {
 title: "Defense - Tactic in 3",
 manifestPath: "/data/pattern-tactics/defense/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/defense/m3",
 progressKey: "tactic-defense-m3",
 trainerKey: "tactic-defense-m3",
 },
 defenseM4: {
 title: "Defense - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/defense/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/defense/m4",
 progressKey: "tactic-defense-m4",
 trainerKey: "tactic-defense-m4",
 },
 advancedPawnM1: {
 title: "Advanced Pawn - Tactic in 1",
 manifestPath: "/data/pattern-tactics/advanced-pawn/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/advanced-pawn/m1",
 progressKey: "tactic-advanced-pawn-m1",
 trainerKey: "tactic-advanced-pawn-m1",
 },
 advancedPawnM2: {
 title: "Advanced Pawn - Tactic in 2",
 manifestPath: "/data/pattern-tactics/advanced-pawn/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/advanced-pawn/m2",
 progressKey: "tactic-advanced-pawn-m2",
 trainerKey: "tactic-advanced-pawn-m2",
 },
 advancedPawnM3: {
 title: "Advanced Pawn - Tactic in 3",
 manifestPath: "/data/pattern-tactics/advanced-pawn/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/advanced-pawn/m3",
 progressKey: "tactic-advanced-pawn-m3",
 trainerKey: "tactic-advanced-pawn-m3",
 },
 advancedPawnM4: {
 title: "Advanced Pawn - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/advanced-pawn/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/advanced-pawn/m4",
 progressKey: "tactic-advanced-pawn-m4",
 trainerKey: "tactic-advanced-pawn-m4",
 },
 quietMoveM1: {
 title: "Quiet Move - Tactic in 1",
 manifestPath: "/data/pattern-tactics/quiet-move/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/quiet-move/m1",
 progressKey: "tactic-quiet-move-m1",
 trainerKey: "tactic-quiet-move-m1",
 },
 quietMoveM2: {
 title: "Quiet Move - Tactic in 2",
 manifestPath: "/data/pattern-tactics/quiet-move/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/quiet-move/m2",
 progressKey: "tactic-quiet-move-m2",
 trainerKey: "tactic-quiet-move-m2",
 },
 quietMoveM3: {
 title: "Quiet Move - Tactic in 3",
 manifestPath: "/data/pattern-tactics/quiet-move/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/quiet-move/m3",
 progressKey: "tactic-quiet-move-m3",
 trainerKey: "tactic-quiet-move-m3",
 },
 quietMoveM4: {
 title: "Quiet Move - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/quiet-move/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/quiet-move/m4",
 progressKey: "tactic-quiet-move-m4",
 trainerKey: "tactic-quiet-move-m4",
 },
 discoveredAttackM1: {
 title: "Discovered Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/discovered-attack/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-attack/m1",
 progressKey: "tactic-discovered-attack-m1",
 trainerKey: "tactic-discovered-attack-m1",
 },
 discoveredAttackM2: {
 title: "Discovered Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/discovered-attack/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-attack/m2",
 progressKey: "tactic-discovered-attack-m2",
 trainerKey: "tactic-discovered-attack-m2",
 },
 discoveredAttackM3: {
 title: "Discovered Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/discovered-attack/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-attack/m3",
 progressKey: "tactic-discovered-attack-m3",
 trainerKey: "tactic-discovered-attack-m3",
 },
 discoveredAttackM4: {
 title: "Discovered Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/discovered-attack/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-attack/m4",
 progressKey: "tactic-discovered-attack-m4",
 trainerKey: "tactic-discovered-attack-m4",
 },
 discoveredCheckM1: {
 title: "Discovered Check - Tactic in 1",
 manifestPath: "/data/pattern-tactics/discovered-check/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-check/m1",
 progressKey: "tactic-discovered-check-m1",
 trainerKey: "tactic-discovered-check-m1",
 },
 discoveredCheckM2: {
 title: "Discovered Check - Tactic in 2",
 manifestPath: "/data/pattern-tactics/discovered-check/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-check/m2",
 progressKey: "tactic-discovered-check-m2",
 trainerKey: "tactic-discovered-check-m2",
 },
 discoveredCheckM3: {
 title: "Discovered Check - Tactic in 3",
 manifestPath: "/data/pattern-tactics/discovered-check/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-check/m3",
 progressKey: "tactic-discovered-check-m3",
 trainerKey: "tactic-discovered-check-m3",
 },
 discoveredCheckM4: {
 title: "Discovered Check - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/discovered-check/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-check/m4",
 progressKey: "tactic-discovered-check-m4",
 trainerKey: "tactic-discovered-check-m4",
 },
 doubleCheckM1: {
 title: "Double Check - Tactic in 1",
 manifestPath: "/data/pattern-tactics/double-check/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/double-check/m1",
 progressKey: "tactic-double-check-m1",
 trainerKey: "tactic-double-check-m1",
 },
 doubleCheckM2: {
 title: "Double Check - Tactic in 2",
 manifestPath: "/data/pattern-tactics/double-check/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/double-check/m2",
 progressKey: "tactic-double-check-m2",
 trainerKey: "tactic-double-check-m2",
 },
 doubleCheckM3: {
 title: "Double Check - Tactic in 3",
 manifestPath: "/data/pattern-tactics/double-check/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/double-check/m3",
 progressKey: "tactic-double-check-m3",
 trainerKey: "tactic-double-check-m3",
 },
 doubleCheckM4: {
 title: "Double Check - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/double-check/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/double-check/m4",
 progressKey: "tactic-double-check-m4",
 trainerKey: "tactic-double-check-m4",
 },
 knightForkM1: {
 title: "Knight Fork / Double Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/knight-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-fork/m1",
 progressKey: "tactic-knight-fork-m1",
 trainerKey: "tactic-knight-fork-m1",
 },
 knightForkM2: {
 title: "Knight Fork / Double Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/knight-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-fork/m2",
 progressKey: "tactic-knight-fork-m2",
 trainerKey: "tactic-knight-fork-m2",
 },
 knightForkM3: {
 title: "Knight Fork / Double Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/knight-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-fork/m3",
 progressKey: "tactic-knight-fork-m3",
 trainerKey: "tactic-knight-fork-m3",
 },
 knightForkM4: {
 title: "Knight Fork / Double Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/knight-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-fork/m4",
 progressKey: "tactic-knight-fork-m4",
 trainerKey: "tactic-knight-fork-m4",
 },
 queenForkM1: {
 title: "Queen Fork / Double Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/queen-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-fork/m1",
 progressKey: "tactic-queen-fork-m1",
 trainerKey: "tactic-queen-fork-m1",
 },
 queenForkM2: {
 title: "Queen Fork / Double Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/queen-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-fork/m2",
 progressKey: "tactic-queen-fork-m2",
 trainerKey: "tactic-queen-fork-m2",
 },
 queenForkM3: {
 title: "Queen Fork / Double Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/queen-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-fork/m3",
 progressKey: "tactic-queen-fork-m3",
 trainerKey: "tactic-queen-fork-m3",
 },
 queenForkM4: {
 title: "Queen Fork / Double Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/queen-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-fork/m4",
 progressKey: "tactic-queen-fork-m4",
 trainerKey: "tactic-queen-fork-m4",
 },
 rookForkM1: {
 title: "Rook Fork / Double Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/rook-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-fork/m1",
 progressKey: "tactic-rook-fork-m1",
 trainerKey: "tactic-rook-fork-m1",
 },
 rookForkM2: {
 title: "Rook Fork / Double Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/rook-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-fork/m2",
 progressKey: "tactic-rook-fork-m2",
 trainerKey: "tactic-rook-fork-m2",
 },
 rookForkM3: {
 title: "Rook Fork / Double Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/rook-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-fork/m3",
 progressKey: "tactic-rook-fork-m3",
 trainerKey: "tactic-rook-fork-m3",
 },
 rookForkM4: {
 title: "Rook Fork / Double Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/rook-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-fork/m4",
 progressKey: "tactic-rook-fork-m4",
 trainerKey: "tactic-rook-fork-m4",
 },
 bishopForkM1: {
 title: "Bishop Fork / Double Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/bishop-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-fork/m1",
 progressKey: "tactic-bishop-fork-m1",
 trainerKey: "tactic-bishop-fork-m1",
 },
 bishopForkM2: {
 title: "Bishop Fork / Double Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/bishop-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-fork/m2",
 progressKey: "tactic-bishop-fork-m2",
 trainerKey: "tactic-bishop-fork-m2",
 },
 bishopForkM3: {
 title: "Bishop Fork / Double Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/bishop-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-fork/m3",
 progressKey: "tactic-bishop-fork-m3",
 trainerKey: "tactic-bishop-fork-m3",
 },
 bishopForkM4: {
 title: "Bishop Fork / Double Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/bishop-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-fork/m4",
 progressKey: "tactic-bishop-fork-m4",
 trainerKey: "tactic-bishop-fork-m4",
 },
 pawnForkM1: {
 title: "Pawn Fork / Double Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/pawn-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-fork/m1",
 progressKey: "tactic-pawn-fork-m1",
 trainerKey: "tactic-pawn-fork-m1",
 },
 pawnForkM2: {
 title: "Pawn Fork / Double Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/pawn-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-fork/m2",
 progressKey: "tactic-pawn-fork-m2",
 trainerKey: "tactic-pawn-fork-m2",
 },
 pawnForkM3: {
 title: "Pawn Fork / Double Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/pawn-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-fork/m3",
 progressKey: "tactic-pawn-fork-m3",
 trainerKey: "tactic-pawn-fork-m3",
 },
 pawnForkM4: {
 title: "Pawn Fork / Double Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/pawn-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-fork/m4",
 progressKey: "tactic-pawn-fork-m4",
 trainerKey: "tactic-pawn-fork-m4",
 },
 kingForkM1: {
 title: "King Fork / Double Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/king-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-fork/m1",
 progressKey: "tactic-king-fork-m1",
 trainerKey: "tactic-king-fork-m1",
 },
 kingForkM2: {
 title: "King Fork / Double Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/king-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-fork/m2",
 progressKey: "tactic-king-fork-m2",
 trainerKey: "tactic-king-fork-m2",
 },
 kingForkM3: {
 title: "King Fork / Double Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/king-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-fork/m3",
 progressKey: "tactic-king-fork-m3",
 trainerKey: "tactic-king-fork-m3",
 },
 kingForkM4: {
 title: "King Fork / Double Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/king-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-fork/m4",
 progressKey: "tactic-king-fork-m4",
 trainerKey: "tactic-king-fork-m4",
 },
 rookPinM1: {
 title: "Rook Pin - Tactic in 1",
 manifestPath: "/data/pattern-tactics/rook-pin/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-pin/m1",
 progressKey: "tactic-rook-pin-m1",
 trainerKey: "tactic-rook-pin-m1",
 },
 rookPinM2: {
 title: "Rook Pin - Tactic in 2",
 manifestPath: "/data/pattern-tactics/rook-pin/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-pin/m2",
 progressKey: "tactic-rook-pin-m2",
 trainerKey: "tactic-rook-pin-m2",
 },
 rookPinM3: {
 title: "Rook Pin - Tactic in 3",
 manifestPath: "/data/pattern-tactics/rook-pin/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-pin/m3",
 progressKey: "tactic-rook-pin-m3",
 trainerKey: "tactic-rook-pin-m3",
 },
 rookPinM4: {
 title: "Rook Pin - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/rook-pin/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-pin/m4",
 progressKey: "tactic-rook-pin-m4",
 trainerKey: "tactic-rook-pin-m4",
 },
 queenPinM1: {
 title: "Queen Pin - Tactic in 1",
 manifestPath: "/data/pattern-tactics/queen-pin/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-pin/m1",
 progressKey: "tactic-queen-pin-m1",
 trainerKey: "tactic-queen-pin-m1",
 },
 queenPinM2: {
 title: "Queen Pin - Tactic in 2",
 manifestPath: "/data/pattern-tactics/queen-pin/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-pin/m2",
 progressKey: "tactic-queen-pin-m2",
 trainerKey: "tactic-queen-pin-m2",
 },
 queenPinM3: {
 title: "Queen Pin - Tactic in 3",
 manifestPath: "/data/pattern-tactics/queen-pin/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-pin/m3",
 progressKey: "tactic-queen-pin-m3",
 trainerKey: "tactic-queen-pin-m3",
 },
 queenPinM4: {
 title: "Queen Pin - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/queen-pin/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-pin/m4",
 progressKey: "tactic-queen-pin-m4",
 trainerKey: "tactic-queen-pin-m4",
 },
 bishopPinM1: {
 title: "Bishop Pin - Tactic in 1",
 manifestPath: "/data/pattern-tactics/bishop-pin/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-pin/m1",
 progressKey: "tactic-bishop-pin-m1",
 trainerKey: "tactic-bishop-pin-m1",
 },
 bishopPinM2: {
 title: "Bishop Pin - Tactic in 2",
 manifestPath: "/data/pattern-tactics/bishop-pin/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-pin/m2",
 progressKey: "tactic-bishop-pin-m2",
 trainerKey: "tactic-bishop-pin-m2",
 },
 bishopPinM3: {
 title: "Bishop Pin - Tactic in 3",
 manifestPath: "/data/pattern-tactics/bishop-pin/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-pin/m3",
 progressKey: "tactic-bishop-pin-m3",
 trainerKey: "tactic-bishop-pin-m3",
 },
 bishopPinM4: {
 title: "Bishop Pin - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/bishop-pin/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-pin/m4",
 progressKey: "tactic-bishop-pin-m4",
 trainerKey: "tactic-bishop-pin-m4",
 },
 rookSkewerM1: {
 title: "Rook Skewer - Tactic in 1",
 manifestPath: "/data/pattern-tactics/rook-skewer/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-skewer/m1",
 progressKey: "tactic-rook-skewer-m1",
 trainerKey: "tactic-rook-skewer-m1",
 },
 rookSkewerM2: {
 title: "Rook Skewer - Tactic in 2",
 manifestPath: "/data/pattern-tactics/rook-skewer/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-skewer/m2",
 progressKey: "tactic-rook-skewer-m2",
 trainerKey: "tactic-rook-skewer-m2",
 },
 rookSkewerM3: {
 title: "Rook Skewer - Tactic in 3",
 manifestPath: "/data/pattern-tactics/rook-skewer/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-skewer/m3",
 progressKey: "tactic-rook-skewer-m3",
 trainerKey: "tactic-rook-skewer-m3",
 },
 rookSkewerM4: {
 title: "Rook Skewer - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/rook-skewer/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-skewer/m4",
 progressKey: "tactic-rook-skewer-m4",
 trainerKey: "tactic-rook-skewer-m4",
 },
 queenSkewerM1: {
 title: "Queen Skewer - Tactic in 1",
 manifestPath: "/data/pattern-tactics/queen-skewer/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-skewer/m1",
 progressKey: "tactic-queen-skewer-m1",
 trainerKey: "tactic-queen-skewer-m1",
 },
 queenSkewerM2: {
 title: "Queen Skewer - Tactic in 2",
 manifestPath: "/data/pattern-tactics/queen-skewer/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-skewer/m2",
 progressKey: "tactic-queen-skewer-m2",
 trainerKey: "tactic-queen-skewer-m2",
 },
 queenSkewerM3: {
 title: "Queen Skewer - Tactic in 3",
 manifestPath: "/data/pattern-tactics/queen-skewer/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-skewer/m3",
 progressKey: "tactic-queen-skewer-m3",
 trainerKey: "tactic-queen-skewer-m3",
 },
 queenSkewerM4: {
 title: "Queen Skewer - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/queen-skewer/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-skewer/m4",
 progressKey: "tactic-queen-skewer-m4",
 trainerKey: "tactic-queen-skewer-m4",
 },
 bishopSkewerM1: {
 title: "Bishop Skewer - Tactic in 1",
 manifestPath: "/data/pattern-tactics/bishop-skewer/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-skewer/m1",
 progressKey: "tactic-bishop-skewer-m1",
 trainerKey: "tactic-bishop-skewer-m1",
 },
 bishopSkewerM2: {
 title: "Bishop Skewer - Tactic in 2",
 manifestPath: "/data/pattern-tactics/bishop-skewer/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-skewer/m2",
 progressKey: "tactic-bishop-skewer-m2",
 trainerKey: "tactic-bishop-skewer-m2",
 },
 bishopSkewerM3: {
 title: "Bishop Skewer - Tactic in 3",
 manifestPath: "/data/pattern-tactics/bishop-skewer/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-skewer/m3",
 progressKey: "tactic-bishop-skewer-m3",
 trainerKey: "tactic-bishop-skewer-m3",
 },
 bishopSkewerM4: {
 title: "Bishop Skewer - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/bishop-skewer/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-skewer/m4",
 progressKey: "tactic-bishop-skewer-m4",
 trainerKey: "tactic-bishop-skewer-m4",
 },
 decoyAttractionM1: {
 title: "Decoy / Attraction - Tactic in 1",
 manifestPath: "/data/pattern-tactics/decoy-attraction/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-attraction/m1",
 progressKey: "tactic-decoy-attraction-m1",
 trainerKey: "tactic-decoy-attraction-m1",
 },
 decoyAttractionM2: {
 title: "Decoy / Attraction - Tactic in 2",
 manifestPath: "/data/pattern-tactics/decoy-attraction/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-attraction/m2",
 progressKey: "tactic-decoy-attraction-m2",
 trainerKey: "tactic-decoy-attraction-m2",
 },
 decoyAttractionM3: {
 title: "Decoy / Attraction - Tactic in 3",
 manifestPath: "/data/pattern-tactics/decoy-attraction/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-attraction/m3",
 progressKey: "tactic-decoy-attraction-m3",
 trainerKey: "tactic-decoy-attraction-m3",
 },
 decoyAttractionM4: {
 title: "Decoy / Attraction - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/decoy-attraction/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-attraction/m4",
 progressKey: "tactic-decoy-attraction-m4",
 trainerKey: "tactic-decoy-attraction-m4",
 },
 deflectionM1: {
 title: "Deflection - Tactic in 1",
 manifestPath: "/data/pattern-tactics/deflection/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/deflection/m1",
 progressKey: "tactic-deflection-m1",
 trainerKey: "tactic-deflection-m1",
 },
 deflectionM2: {
 title: "Deflection - Tactic in 2",
 manifestPath: "/data/pattern-tactics/deflection/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/deflection/m2",
 progressKey: "tactic-deflection-m2",
 trainerKey: "tactic-deflection-m2",
 },
 deflectionM3: {
 title: "Deflection - Tactic in 3",
 manifestPath: "/data/pattern-tactics/deflection/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/deflection/m3",
 progressKey: "tactic-deflection-m3",
 trainerKey: "tactic-deflection-m3",
 },
 deflectionM4: {
 title: "Deflection - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/deflection/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/deflection/m4",
 progressKey: "tactic-deflection-m4",
 trainerKey: "tactic-deflection-m4",
 },
 decoyDeflectionM2: {
 title: "Decoy + Deflection - Tactic in 2",
 manifestPath: "/data/pattern-tactics/decoy-deflection/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-deflection/m2",
 progressKey: "tactic-decoy-deflection-m2",
 trainerKey: "tactic-decoy-deflection-m2",
 },
 decoyDeflectionM3: {
 title: "Decoy + Deflection - Tactic in 3",
 manifestPath: "/data/pattern-tactics/decoy-deflection/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-deflection/m3",
 progressKey: "tactic-decoy-deflection-m3",
 trainerKey: "tactic-decoy-deflection-m3",
 },
 decoyDeflectionM4: {
 title: "Decoy + Deflection - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/decoy-deflection/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-deflection/m4",
 progressKey: "tactic-decoy-deflection-m4",
 trainerKey: "tactic-decoy-deflection-m4",
 },
 hangingPieceM1: {
 title: "Hanging Piece - Tactic in 1",
 manifestPath: "/data/pattern-tactics/hanging-piece/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/hanging-piece/m1",
 progressKey: "tactic-hanging-piece-m1",
 trainerKey: "tactic-hanging-piece-m1",
 },
 hangingPieceM2: {
 title: "Hanging Piece - Tactic in 2",
 manifestPath: "/data/pattern-tactics/hanging-piece/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/hanging-piece/m2",
 progressKey: "tactic-hanging-piece-m2",
 trainerKey: "tactic-hanging-piece-m2",
 },
 hangingPieceM3: {
 title: "Hanging Piece - Tactic in 3",
 manifestPath: "/data/pattern-tactics/hanging-piece/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/hanging-piece/m3",
 progressKey: "tactic-hanging-piece-m3",
 trainerKey: "tactic-hanging-piece-m3",
 },
 hangingPieceM4: {
 title: "Hanging Piece - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/hanging-piece/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/hanging-piece/m4",
 progressKey: "tactic-hanging-piece-m4",
 trainerKey: "tactic-hanging-piece-m4",
 },
 trappedPieceM1: {
 title: "Trapped Piece - Tactic in 1",
 manifestPath: "/data/pattern-tactics/trapped-piece/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/trapped-piece/m1",
 progressKey: "tactic-trapped-piece-m1",
 trainerKey: "tactic-trapped-piece-m1",
 },
 trappedPieceM2: {
 title: "Trapped Piece - Tactic in 2",
 manifestPath: "/data/pattern-tactics/trapped-piece/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/trapped-piece/m2",
 progressKey: "tactic-trapped-piece-m2",
 trainerKey: "tactic-trapped-piece-m2",
 },
 trappedPieceM3: {
 title: "Trapped Piece - Tactic in 3",
 manifestPath: "/data/pattern-tactics/trapped-piece/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/trapped-piece/m3",
 progressKey: "tactic-trapped-piece-m3",
 trainerKey: "tactic-trapped-piece-m3",
 },
 trappedPieceM4: {
 title: "Trapped Piece - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/trapped-piece/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/trapped-piece/m4",
 progressKey: "tactic-trapped-piece-m4",
 trainerKey: "tactic-trapped-piece-m4",
 },
 removeTheDefenderM1: {
 title: "Remove the Defender - Tactic in 1",
 manifestPath: "/data/pattern-tactics/remove-the-defender/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/remove-the-defender/m1",
 progressKey: "tactic-remove-the-defender-m1",
 trainerKey: "tactic-remove-the-defender-m1",
 },
 removeTheDefenderM2: {
 title: "Remove the Defender - Tactic in 2",
 manifestPath: "/data/pattern-tactics/remove-the-defender/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/remove-the-defender/m2",
 progressKey: "tactic-remove-the-defender-m2",
 trainerKey: "tactic-remove-the-defender-m2",
 },
 removeTheDefenderM3: {
 title: "Remove the Defender - Tactic in 3",
 manifestPath: "/data/pattern-tactics/remove-the-defender/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/remove-the-defender/m3",
 progressKey: "tactic-remove-the-defender-m3",
 trainerKey: "tactic-remove-the-defender-m3",
 },
 removeTheDefenderM4: {
 title: "Remove the Defender - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/remove-the-defender/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/remove-the-defender/m4",
 progressKey: "tactic-remove-the-defender-m4",
 trainerKey: "tactic-remove-the-defender-m4",
 },
 vulnerableKingM1: {
 title: "Vulnerable / Exposed King - Tactic in 1",
 manifestPath: "/data/pattern-tactics/vulnerable-king/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/vulnerable-king/m1",
 progressKey: "tactic-vulnerable-king-m1",
 trainerKey: "tactic-vulnerable-king-m1",
 },
 vulnerableKingM2: {
 title: "Vulnerable / Exposed King - Tactic in 2",
 manifestPath: "/data/pattern-tactics/vulnerable-king/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/vulnerable-king/m2",
 progressKey: "tactic-vulnerable-king-m2",
 trainerKey: "tactic-vulnerable-king-m2",
 },
 vulnerableKingM3: {
 title: "Vulnerable / Exposed King - Tactic in 3",
 manifestPath: "/data/pattern-tactics/vulnerable-king/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/vulnerable-king/m3",
 progressKey: "tactic-vulnerable-king-m3",
 trainerKey: "tactic-vulnerable-king-m3",
 },
 vulnerableKingM4: {
 title: "Vulnerable / Exposed King - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/vulnerable-king/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/vulnerable-king/m4",
 progressKey: "tactic-vulnerable-king-m4",
 trainerKey: "tactic-vulnerable-king-m4",
 },
 kingsideAttackM1: {
 title: "Kingside Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/kingside-attack/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/kingside-attack/m1",
 progressKey: "tactic-kingside-attack-m1",
 trainerKey: "tactic-kingside-attack-m1",
 },
 kingsideAttackM2: {
 title: "Kingside Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/kingside-attack/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/kingside-attack/m2",
 progressKey: "tactic-kingside-attack-m2",
 trainerKey: "tactic-kingside-attack-m2",
 },
 kingsideAttackM3: {
 title: "Kingside Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/kingside-attack/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/kingside-attack/m3",
 progressKey: "tactic-kingside-attack-m3",
 trainerKey: "tactic-kingside-attack-m3",
 },
 kingsideAttackM4: {
 title: "Kingside Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/kingside-attack/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/kingside-attack/m4",
 progressKey: "tactic-kingside-attack-m4",
 trainerKey: "tactic-kingside-attack-m4",
 },
 queensideAttackM1: {
 title: "Queenside Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/queenside-attack/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queenside-attack/m1",
 progressKey: "tactic-queenside-attack-m1",
 trainerKey: "tactic-queenside-attack-m1",
 },
 queensideAttackM2: {
 title: "Queenside Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/queenside-attack/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queenside-attack/m2",
 progressKey: "tactic-queenside-attack-m2",
 trainerKey: "tactic-queenside-attack-m2",
 },
 queensideAttackM3: {
 title: "Queenside Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/queenside-attack/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queenside-attack/m3",
 progressKey: "tactic-queenside-attack-m3",
 trainerKey: "tactic-queenside-attack-m3",
 },
 queensideAttackM4: {
 title: "Queenside Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/queenside-attack/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queenside-attack/m4",
 progressKey: "tactic-queenside-attack-m4",
 trainerKey: "tactic-queenside-attack-m4",
 },
 attackingF2F7M1: {
 title: "Attacking f2/f7 - Tactic in 1",
 manifestPath: "/data/pattern-tactics/attacking-f2-f7/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/attacking-f2-f7/m1",
 progressKey: "tactic-attacking-f2-f7-m1",
 trainerKey: "tactic-attacking-f2-f7-m1",
 },
 attackingF2F7M2: {
 title: "Attacking f2/f7 - Tactic in 2",
 manifestPath: "/data/pattern-tactics/attacking-f2-f7/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/attacking-f2-f7/m2",
 progressKey: "tactic-attacking-f2-f7-m2",
 trainerKey: "tactic-attacking-f2-f7-m2",
 },
 attackingF2F7M3: {
 title: "Attacking f2/f7 - Tactic in 3",
 manifestPath: "/data/pattern-tactics/attacking-f2-f7/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/attacking-f2-f7/m3",
 progressKey: "tactic-attacking-f2-f7-m3",
 trainerKey: "tactic-attacking-f2-f7-m3",
 },
 attackingF2F7M4: {
 title: "Attacking f2/f7 - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/attacking-f2-f7/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/attacking-f2-f7/m4",
 progressKey: "tactic-attacking-f2-f7-m4",
 trainerKey: "tactic-attacking-f2-f7-m4",
 },
 queenSacrificeM2: {
 title: "Queen Sacrifice - Tactic in 2",
 manifestPath: "/data/pattern-tactics/queen-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-sacrifice/m2",
 progressKey: "tactic-queen-sacrifice-m2",
 trainerKey: "tactic-queen-sacrifice-m2",
 },
 queenSacrificeM3: {
 title: "Queen Sacrifice - Tactic in 3",
 manifestPath: "/data/pattern-tactics/queen-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-sacrifice/m3",
 progressKey: "tactic-queen-sacrifice-m3",
 trainerKey: "tactic-queen-sacrifice-m3",
 },
 queenSacrificeM4: {
 title: "Queen Sacrifice - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/queen-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-sacrifice/m4",
 progressKey: "tactic-queen-sacrifice-m4",
 trainerKey: "tactic-queen-sacrifice-m4",
 },
 rookSacrificeM2: {
 title: "Rook Sacrifice - Tactic in 2",
 manifestPath: "/data/pattern-tactics/rook-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-sacrifice/m2",
 progressKey: "tactic-rook-sacrifice-m2",
 trainerKey: "tactic-rook-sacrifice-m2",
 },
 rookSacrificeM3: {
 title: "Rook Sacrifice - Tactic in 3",
 manifestPath: "/data/pattern-tactics/rook-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-sacrifice/m3",
 progressKey: "tactic-rook-sacrifice-m3",
 trainerKey: "tactic-rook-sacrifice-m3",
 },
 rookSacrificeM4: {
 title: "Rook Sacrifice - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/rook-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-sacrifice/m4",
 progressKey: "tactic-rook-sacrifice-m4",
 trainerKey: "tactic-rook-sacrifice-m4",
 },
 bishopSacrificeM2: {
 title: "Bishop Sacrifice - Tactic in 2",
 manifestPath: "/data/pattern-tactics/bishop-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-sacrifice/m2",
 progressKey: "tactic-bishop-sacrifice-m2",
 trainerKey: "tactic-bishop-sacrifice-m2",
 },
 bishopSacrificeM3: {
 title: "Bishop Sacrifice - Tactic in 3",
 manifestPath: "/data/pattern-tactics/bishop-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-sacrifice/m3",
 progressKey: "tactic-bishop-sacrifice-m3",
 trainerKey: "tactic-bishop-sacrifice-m3",
 },
 bishopSacrificeM4: {
 title: "Bishop Sacrifice - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/bishop-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-sacrifice/m4",
 progressKey: "tactic-bishop-sacrifice-m4",
 trainerKey: "tactic-bishop-sacrifice-m4",
 },
 knightSacrificeM2: {
 title: "Knight Sacrifice - Tactic in 2",
 manifestPath: "/data/pattern-tactics/knight-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-sacrifice/m2",
 progressKey: "tactic-knight-sacrifice-m2",
 trainerKey: "tactic-knight-sacrifice-m2",
 },
 knightSacrificeM3: {
 title: "Knight Sacrifice - Tactic in 3",
 manifestPath: "/data/pattern-tactics/knight-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-sacrifice/m3",
 progressKey: "tactic-knight-sacrifice-m3",
 trainerKey: "tactic-knight-sacrifice-m3",
 },
 knightSacrificeM4: {
 title: "Knight Sacrifice - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/knight-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-sacrifice/m4",
 progressKey: "tactic-knight-sacrifice-m4",
 trainerKey: "tactic-knight-sacrifice-m4",
 },
 pawnSacrificeM2: {
 title: "Pawn Sacrifice - Tactic in 2",
 manifestPath: "/data/pattern-tactics/pawn-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-sacrifice/m2",
 progressKey: "tactic-pawn-sacrifice-m2",
 trainerKey: "tactic-pawn-sacrifice-m2",
 },
 pawnSacrificeM3: {
 title: "Pawn Sacrifice - Tactic in 3",
 manifestPath: "/data/pattern-tactics/pawn-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-sacrifice/m3",
 progressKey: "tactic-pawn-sacrifice-m3",
 trainerKey: "tactic-pawn-sacrifice-m3",
 },
 pawnSacrificeM4: {
 title: "Pawn Sacrifice - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/pawn-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-sacrifice/m4",
 progressKey: "tactic-pawn-sacrifice-m4",
 trainerKey: "tactic-pawn-sacrifice-m4",
 },
 clearanceM1: {
 title: "Clearance - Tactic in 1",
 manifestPath: "/data/pattern-tactics/clearance/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance/m1",
 progressKey: "tactic-clearance-m1",
 trainerKey: "tactic-clearance-m1",
 },
 clearanceM2: {
 title: "Clearance - Tactic in 2",
 manifestPath: "/data/pattern-tactics/clearance/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance/m2",
 progressKey: "tactic-clearance-m2",
 trainerKey: "tactic-clearance-m2",
 },
 clearanceM3: {
 title: "Clearance - Tactic in 3",
 manifestPath: "/data/pattern-tactics/clearance/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance/m3",
 progressKey: "tactic-clearance-m3",
 trainerKey: "tactic-clearance-m3",
 },
 clearanceM4: {
 title: "Clearance - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/clearance/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance/m4",
 progressKey: "tactic-clearance-m4",
  trainerKey: "tactic-clearance-m4",
 },
 diagonalClearanceM1: {
 title: "Diagonal Clearance - Tactic in 1",
 manifestPath: "/data/pattern-tactics/diagonal-clearance/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/diagonal-clearance/m1",
 progressKey: "tactic-diagonal-clearance-m1",
 trainerKey: "tactic-diagonal-clearance-m1",
 },
 fileClearanceM1: {
 title: "File Clearance - Tactic in 1",
 manifestPath: "/data/pattern-tactics/file-clearance/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/file-clearance/m1",
 progressKey: "tactic-file-clearance-m1",
 trainerKey: "tactic-file-clearance-m1",
 },
 fileClearanceM2: {
 title: "File Clearance - Tactic in 2",
 manifestPath: "/data/pattern-tactics/file-clearance/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/file-clearance/m2",
 progressKey: "tactic-file-clearance-m2",
 trainerKey: "tactic-file-clearance-m2",
 },
 rankClearanceM1: {
 title: "Rank Clearance - Tactic in 1",
 manifestPath: "/data/pattern-tactics/rank-clearance/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rank-clearance/m1",
 progressKey: "tactic-rank-clearance-m1",
 trainerKey: "tactic-rank-clearance-m1",
 },
 rankClearanceM2: {
 title: "Rank Clearance - Tactic in 2",
 manifestPath: "/data/pattern-tactics/rank-clearance/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rank-clearance/m2",
 progressKey: "tactic-rank-clearance-m2",
 trainerKey: "tactic-rank-clearance-m2",
 },
 clearanceSacrificeM1: {
 title: "Clearance Sacrifice - Tactic in 1",
 manifestPath: "/data/pattern-tactics/clearance-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance-sacrifice/m1",
 progressKey: "tactic-clearance-sacrifice-m1",
 trainerKey: "tactic-clearance-sacrifice-m1",
 },
 clearanceSacrificeM2: {
 title: "Clearance Sacrifice - Tactic in 2",
 manifestPath: "/data/pattern-tactics/clearance-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance-sacrifice/m2",
 progressKey: "tactic-clearance-sacrifice-m2",
 trainerKey: "tactic-clearance-sacrifice-m2",
 },
 clearanceSacrificeM3: {
 title: "Clearance Sacrifice - Tactic in 3",
 manifestPath: "/data/pattern-tactics/clearance-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance-sacrifice/m3",
 progressKey: "tactic-clearance-sacrifice-m3",
 trainerKey: "tactic-clearance-sacrifice-m3",
 },
 clearanceSacrificeM4: {
 title: "Clearance Sacrifice - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/clearance-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance-sacrifice/m4",
 progressKey: "tactic-clearance-sacrifice-m4",
 trainerKey: "tactic-clearance-sacrifice-m4",
 },
 interferenceM1: {
 title: "Interference - Tactic in 1",
 manifestPath: "/data/pattern-tactics/interference/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference/m1",
 progressKey: "tactic-interference-m1",
 trainerKey: "tactic-interference-m1",
 },
 interferenceM2: {
 title: "Interference - Tactic in 2",
 manifestPath: "/data/pattern-tactics/interference/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference/m2",
 progressKey: "tactic-interference-m2",
 trainerKey: "tactic-interference-m2",
 },
 interferenceM3: {
 title: "Interference - Tactic in 3",
 manifestPath: "/data/pattern-tactics/interference/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference/m3",
 progressKey: "tactic-interference-m3",
 trainerKey: "tactic-interference-m3",
 },
 interferenceM4: {
 title: "Interference - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/interference/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference/m4",
 progressKey: "tactic-interference-m4",
 trainerKey: "tactic-interference-m4",
 },
 interferenceSacrificeM1: {
 title: "Interference Sacrifice - Tactic in 1",
 manifestPath: "/data/pattern-tactics/interference-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference-sacrifice/m1",
 progressKey: "tactic-interference-sacrifice-m1",
 trainerKey: "tactic-interference-sacrifice-m1",
 },
 interferenceSacrificeM2: {
 title: "Interference Sacrifice - Tactic in 2",
 manifestPath: "/data/pattern-tactics/interference-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference-sacrifice/m2",
 progressKey: "tactic-interference-sacrifice-m2",
 trainerKey: "tactic-interference-sacrifice-m2",
 },
 interferenceSacrificeM3: {
 title: "Interference Sacrifice - Tactic in 3",
 manifestPath: "/data/pattern-tactics/interference-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference-sacrifice/m3",
 progressKey: "tactic-interference-sacrifice-m3",
 trainerKey: "tactic-interference-sacrifice-m3",
 },
 interferenceSacrificeM4: {
 title: "Interference Sacrifice - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/interference-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference-sacrifice/m4",
 progressKey: "tactic-interference-sacrifice-m4",
 trainerKey: "tactic-interference-sacrifice-m4",
 },
 queenXrayM1: {
 title: "Queen X-Ray Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/queen-xray/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-xray/m1",
 progressKey: "tactic-queen-xray-m1",
 trainerKey: "tactic-queen-xray-m1",
 },
 queenXrayM2: {
 title: "Queen X-Ray Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/queen-xray/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-xray/m2",
 progressKey: "tactic-queen-xray-m2",
 trainerKey: "tactic-queen-xray-m2",
 },
 queenXrayM3: {
 title: "Queen X-Ray Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/queen-xray/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-xray/m3",
 progressKey: "tactic-queen-xray-m3",
 trainerKey: "tactic-queen-xray-m3",
 },
 queenXrayM4: {
 title: "Queen X-Ray Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/queen-xray/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-xray/m4",
 progressKey: "tactic-queen-xray-m4",
 trainerKey: "tactic-queen-xray-m4",
 },
 rookXrayM1: {
 title: "Rook X-Ray Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/rook-xray/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-xray/m1",
 progressKey: "tactic-rook-xray-m1",
 trainerKey: "tactic-rook-xray-m1",
 },
 rookXrayM2: {
 title: "Rook X-Ray Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/rook-xray/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-xray/m2",
 progressKey: "tactic-rook-xray-m2",
 trainerKey: "tactic-rook-xray-m2",
 },
 rookXrayM3: {
 title: "Rook X-Ray Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/rook-xray/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-xray/m3",
 progressKey: "tactic-rook-xray-m3",
 trainerKey: "tactic-rook-xray-m3",
 },
 rookXrayM4: {
 title: "Rook X-Ray Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/rook-xray/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-xray/m4",
 progressKey: "tactic-rook-xray-m4",
 trainerKey: "tactic-rook-xray-m4",
 },
 bishopXrayM1: {
 title: "Bishop X-Ray Attack - Tactic in 1",
 manifestPath: "/data/pattern-tactics/bishop-xray/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-xray/m1",
 progressKey: "tactic-bishop-xray-m1",
 trainerKey: "tactic-bishop-xray-m1",
 },
 bishopXrayM2: {
 title: "Bishop X-Ray Attack - Tactic in 2",
 manifestPath: "/data/pattern-tactics/bishop-xray/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-xray/m2",
 progressKey: "tactic-bishop-xray-m2",
 trainerKey: "tactic-bishop-xray-m2",
 },
 bishopXrayM3: {
 title: "Bishop X-Ray Attack - Tactic in 3",
 manifestPath: "/data/pattern-tactics/bishop-xray/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-xray/m3",
 progressKey: "tactic-bishop-xray-m3",
 trainerKey: "tactic-bishop-xray-m3",
 },
 bishopXrayM4: {
 title: "Bishop X-Ray Attack - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/bishop-xray/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-xray/m4",
 progressKey: "tactic-bishop-xray-m4",
 trainerKey: "tactic-bishop-xray-m4",
 },
 promotionM1: {
 title: "Promotion - Tactic in 1",
 manifestPath: "/data/pattern-tactics/promotion/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/promotion/m1",
 progressKey: "tactic-promotion-m1",
 trainerKey: "tactic-promotion-m1",
 },
 promotionM2: {
 title: "Promotion - Tactic in 2",
 manifestPath: "/data/pattern-tactics/promotion/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/promotion/m2",
 progressKey: "tactic-promotion-m2",
 trainerKey: "tactic-promotion-m2",
 },
 promotionM3: {
 title: "Promotion - Tactic in 3",
 manifestPath: "/data/pattern-tactics/promotion/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/promotion/m3",
 progressKey: "tactic-promotion-m3",
 trainerKey: "tactic-promotion-m3",
 },
 promotionM4: {
 title: "Promotion - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/promotion/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/promotion/m4",
 progressKey: "tactic-promotion-m4",
 trainerKey: "tactic-promotion-m4",
 },
 underpromotionM1: {
 title: "Underpromotion - Tactic in 1",
 manifestPath: "/data/pattern-tactics/underpromotion/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/underpromotion/m1",
 progressKey: "tactic-underpromotion-m1",
 trainerKey: "tactic-underpromotion-m1",
 },
 underpromotionM2: {
 title: "Underpromotion - Tactic in 2",
 manifestPath: "/data/pattern-tactics/underpromotion/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/underpromotion/m2",
 progressKey: "tactic-underpromotion-m2",
 trainerKey: "tactic-underpromotion-m2",
 },
 underpromotionM3: {
 title: "Underpromotion - Tactic in 3",
 manifestPath: "/data/pattern-tactics/underpromotion/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/underpromotion/m3",
 progressKey: "tactic-underpromotion-m3",
 trainerKey: "tactic-underpromotion-m3",
 },
 underpromotionM4: {
 title: "Underpromotion - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/underpromotion/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/underpromotion/m4",
 progressKey: "tactic-underpromotion-m4",
 trainerKey: "tactic-underpromotion-m4",
 },
 knightUnderpromotionM1: {
 title: "Knight Underpromotion - Tactic in 1",
 manifestPath: "/data/pattern-tactics/knight-underpromotion/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-underpromotion/m1",
 progressKey: "tactic-knight-underpromotion-m1",
 trainerKey: "tactic-knight-underpromotion-m1",
 },
 knightUnderpromotionM2: {
 title: "Knight Underpromotion - Tactic in 2",
 manifestPath: "/data/pattern-tactics/knight-underpromotion/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-underpromotion/m2",
 progressKey: "tactic-knight-underpromotion-m2",
 trainerKey: "tactic-knight-underpromotion-m2",
 },
 knightUnderpromotionM3: {
 title: "Knight Underpromotion - Tactic in 3",
 manifestPath: "/data/pattern-tactics/knight-underpromotion/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-underpromotion/m3",
 progressKey: "tactic-knight-underpromotion-m3",
 trainerKey: "tactic-knight-underpromotion-m3",
 },
 knightUnderpromotionM4: {
 title: "Knight Underpromotion - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/knight-underpromotion/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-underpromotion/m4",
 progressKey: "tactic-knight-underpromotion-m4",
 trainerKey: "tactic-knight-underpromotion-m4",
 },
 enPassantM1: {
 title: "En Passant - Tactic in 1",
 manifestPath: "/data/pattern-tactics/en-passant/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/en-passant/m1",
 progressKey: "tactic-en-passant-m1",
 trainerKey: "tactic-en-passant-m1",
 },
 enPassantM2: {
 title: "En Passant - Tactic in 2",
 manifestPath: "/data/pattern-tactics/en-passant/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/en-passant/m2",
 progressKey: "tactic-en-passant-m2",
 trainerKey: "tactic-en-passant-m2",
 },
 enPassantM3: {
 title: "En Passant - Tactic in 3",
 manifestPath: "/data/pattern-tactics/en-passant/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/en-passant/m3",
 progressKey: "tactic-en-passant-m3",
 trainerKey: "tactic-en-passant-m3",
 },
 enPassantM4: {
 title: "En Passant - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/en-passant/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/en-passant/m4",
 progressKey: "tactic-en-passant-m4",
 trainerKey: "tactic-en-passant-m4",
 },
 zugzwangM1: {
 title: "Zugzwang - Tactic in 1",
 manifestPath: "/data/pattern-tactics/zugzwang/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/zugzwang/m1",
 progressKey: "tactic-zugzwang-m1",
 trainerKey: "tactic-zugzwang-m1",
 },
 zugzwangM2: {
 title: "Zugzwang - Tactic in 2",
 manifestPath: "/data/pattern-tactics/zugzwang/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/zugzwang/m2",
 progressKey: "tactic-zugzwang-m2",
 trainerKey: "tactic-zugzwang-m2",
 },
 zugzwangM3: {
 title: "Zugzwang - Tactic in 3",
 manifestPath: "/data/pattern-tactics/zugzwang/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/zugzwang/m3",
 progressKey: "tactic-zugzwang-m3",
 trainerKey: "tactic-zugzwang-m3",
 },
 zugzwangM4: {
 title: "Zugzwang - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/zugzwang/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/zugzwang/m4",
 progressKey: "tactic-zugzwang-m4",
  trainerKey: "tactic-zugzwang-m4",
 },
 zwischencheckM1: {
 title: "Zwischencheck - Tactic in 1",
 manifestPath: "/data/pattern-tactics/zwischencheck/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/zwischencheck/m1",
 progressKey: "tactic-zwischencheck-m1",
 trainerKey: "tactic-zwischencheck-m1",
 },
 zwischenzugM1: {
 title: "Zwischenzug / Intermezzo - Tactic in 1",
 manifestPath: "/data/pattern-tactics/zwischenzug/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/zwischenzug/m1",
 progressKey: "tactic-zwischenzug-m1",
 trainerKey: "tactic-zwischenzug-m1",
 },
 zwischenzugM2: {
 title: "Zwischenzug / Intermezzo - Tactic in 2",
 manifestPath: "/data/pattern-tactics/zwischenzug/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/zwischenzug/m2",
 progressKey: "tactic-zwischenzug-m2",
 trainerKey: "tactic-zwischenzug-m2",
 },
 zwischenzugM3: {
 title: "Zwischenzug / Intermezzo - Tactic in 3",
 manifestPath: "/data/pattern-tactics/zwischenzug/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/zwischenzug/m3",
 progressKey: "tactic-zwischenzug-m3",
 trainerKey: "tactic-zwischenzug-m3",
 },
 zwischenzugM4: {
 title: "Zwischenzug / Intermezzo - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/zwischenzug/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/zwischenzug/m4",
 progressKey: "tactic-zwischenzug-m4",
 trainerKey: "tactic-zwischenzug-m4",
 },
 mixedM1: {
 title: "Mixed - Tactic in 1",
 manifestPath: "/data/pattern-tactics/mixed/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/mixed/m1",
 progressKey: "tactic-mixed-m1",
 trainerKey: "tactic-mixed-m1",
 },
 mixedM2: {
 title: "Mixed - Tactic in 2",
 manifestPath: "/data/pattern-tactics/mixed/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/mixed/m2",
 progressKey: "tactic-mixed-m2",
 trainerKey: "tactic-mixed-m2",
 },
 mixedM3: {
 title: "Mixed - Tactic in 3",
 manifestPath: "/data/pattern-tactics/mixed/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/mixed/m3",
 progressKey: "tactic-mixed-m3",
 trainerKey: "tactic-mixed-m3",
 },
 mixedM4: {
 title: "Mixed - Tactic in 4+",
 manifestPath: "/data/pattern-tactics/mixed/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/mixed/m4",
 progressKey: "tactic-mixed-m4",
 trainerKey: "tactic-mixed-m4",
 },
}

const generatedVerifiedFinalConfigs = Object.fromEntries(
 VERIFIED_FINAL_TACTIC_COURSES.map((course) => {
  const level = `m${course.stage}`
  const titleSuffix = course.stage === 4 ? "4+" : String(course.stage)
  return [`${level}/${course.theme}`, {
   title: `${course.label} - Tactic in ${titleSuffix}`,
   manifestPath: `${course.learnerDataBasePath}/manifest.json`,
   dataBasePath: course.learnerDataBasePath,
   progressKey: course.trainerKey,
   trainerKey: course.trainerKey,
  }]
 }),
)

// The generated final taxonomy is applied last, so every active focused route
// is derived from the reviewed corpus rather than the historical menu list.
const legacyPatternTacticConfigByRoute = {
 "m1/defense": patternTacticPageConfigs.defenseM1,
 "m2/defense": patternTacticPageConfigs.defenseM2,
 "m3/defense": patternTacticPageConfigs.defenseM3,
 "m4/defense": patternTacticPageConfigs.defenseM4,
 "m1/advanced-pawn": patternTacticPageConfigs.advancedPawnM1,
 "m2/advanced-pawn": patternTacticPageConfigs.advancedPawnM2,
 "m3/advanced-pawn": patternTacticPageConfigs.advancedPawnM3,
 "m4/advanced-pawn": patternTacticPageConfigs.advancedPawnM4,
 "m1/quiet-move": patternTacticPageConfigs.quietMoveM1,
 "m2/quiet-move": patternTacticPageConfigs.quietMoveM2,
 "m3/quiet-move": patternTacticPageConfigs.quietMoveM3,
 "m4/quiet-move": patternTacticPageConfigs.quietMoveM4,
 "m1/discovered-attack": patternTacticPageConfigs.discoveredAttackM1,
 "m2/discovered-attack": patternTacticPageConfigs.discoveredAttackM2,
 "m3/discovered-attack": patternTacticPageConfigs.discoveredAttackM3,
 "m4/discovered-attack": patternTacticPageConfigs.discoveredAttackM4,
 "m1/discovered-check": patternTacticPageConfigs.discoveredCheckM1,
 "m2/discovered-check": patternTacticPageConfigs.discoveredCheckM2,
 "m3/discovered-check": patternTacticPageConfigs.discoveredCheckM3,
 "m4/discovered-check": patternTacticPageConfigs.discoveredCheckM4,
 "m1/double-check": patternTacticPageConfigs.doubleCheckM1,
 "m2/double-check": patternTacticPageConfigs.doubleCheckM2,
 "m3/double-check": patternTacticPageConfigs.doubleCheckM3,
 "m4/double-check": patternTacticPageConfigs.doubleCheckM4,
 "m1/knight-fork": patternTacticPageConfigs.knightForkM1,
 "m2/knight-fork": patternTacticPageConfigs.knightForkM2,
 "m3/knight-fork": patternTacticPageConfigs.knightForkM3,
 "m4/knight-fork": patternTacticPageConfigs.knightForkM4,
 "m1/queen-fork": patternTacticPageConfigs.queenForkM1,
 "m2/queen-fork": patternTacticPageConfigs.queenForkM2,
 "m3/queen-fork": patternTacticPageConfigs.queenForkM3,
 "m4/queen-fork": patternTacticPageConfigs.queenForkM4,
 "m1/rook-fork": patternTacticPageConfigs.rookForkM1,
 "m2/rook-fork": patternTacticPageConfigs.rookForkM2,
 "m3/rook-fork": patternTacticPageConfigs.rookForkM3,
 "m4/rook-fork": patternTacticPageConfigs.rookForkM4,
 "m1/bishop-fork": patternTacticPageConfigs.bishopForkM1,
 "m2/bishop-fork": patternTacticPageConfigs.bishopForkM2,
 "m3/bishop-fork": patternTacticPageConfigs.bishopForkM3,
 "m4/bishop-fork": patternTacticPageConfigs.bishopForkM4,
 "m1/pawn-fork": patternTacticPageConfigs.pawnForkM1,
 "m2/pawn-fork": patternTacticPageConfigs.pawnForkM2,
 "m3/pawn-fork": patternTacticPageConfigs.pawnForkM3,
 "m4/pawn-fork": patternTacticPageConfigs.pawnForkM4,
 "m1/king-fork": patternTacticPageConfigs.kingForkM1,
 "m2/king-fork": patternTacticPageConfigs.kingForkM2,
 "m3/king-fork": patternTacticPageConfigs.kingForkM3,
 "m4/king-fork": patternTacticPageConfigs.kingForkM4,
 "m1/rook-pin": patternTacticPageConfigs.rookPinM1,
 "m2/rook-pin": patternTacticPageConfigs.rookPinM2,
 "m3/rook-pin": patternTacticPageConfigs.rookPinM3,
 "m4/rook-pin": patternTacticPageConfigs.rookPinM4,
 "m1/queen-pin": patternTacticPageConfigs.queenPinM1,
 "m2/queen-pin": patternTacticPageConfigs.queenPinM2,
 "m3/queen-pin": patternTacticPageConfigs.queenPinM3,
 "m4/queen-pin": patternTacticPageConfigs.queenPinM4,
 "m1/bishop-pin": patternTacticPageConfigs.bishopPinM1,
 "m2/bishop-pin": patternTacticPageConfigs.bishopPinM2,
 "m3/bishop-pin": patternTacticPageConfigs.bishopPinM3,
 "m4/bishop-pin": patternTacticPageConfigs.bishopPinM4,
 "m1/rook-skewer": patternTacticPageConfigs.rookSkewerM1,
 "m2/rook-skewer": patternTacticPageConfigs.rookSkewerM2,
 "m3/rook-skewer": patternTacticPageConfigs.rookSkewerM3,
 "m4/rook-skewer": patternTacticPageConfigs.rookSkewerM4,
 "m1/queen-skewer": patternTacticPageConfigs.queenSkewerM1,
 "m2/queen-skewer": patternTacticPageConfigs.queenSkewerM2,
 "m3/queen-skewer": patternTacticPageConfigs.queenSkewerM3,
 "m4/queen-skewer": patternTacticPageConfigs.queenSkewerM4,
 "m1/bishop-skewer": patternTacticPageConfigs.bishopSkewerM1,
 "m2/bishop-skewer": patternTacticPageConfigs.bishopSkewerM2,
 "m3/bishop-skewer": patternTacticPageConfigs.bishopSkewerM3,
 "m4/bishop-skewer": patternTacticPageConfigs.bishopSkewerM4,
 "m1/decoy-attraction": patternTacticPageConfigs.decoyAttractionM1,
 "m2/decoy-attraction": patternTacticPageConfigs.decoyAttractionM2,
 "m3/decoy-attraction": patternTacticPageConfigs.decoyAttractionM3,
 "m4/decoy-attraction": patternTacticPageConfigs.decoyAttractionM4,
 "m1/deflection": patternTacticPageConfigs.deflectionM1,
 "m2/deflection": patternTacticPageConfigs.deflectionM2,
 "m3/deflection": patternTacticPageConfigs.deflectionM3,
 "m4/deflection": patternTacticPageConfigs.deflectionM4,
 "m2/decoy-deflection": patternTacticPageConfigs.decoyDeflectionM2,
 "m3/decoy-deflection": patternTacticPageConfigs.decoyDeflectionM3,
 "m4/decoy-deflection": patternTacticPageConfigs.decoyDeflectionM4,
 "m1/hanging-piece": patternTacticPageConfigs.hangingPieceM1,
 "m2/hanging-piece": patternTacticPageConfigs.hangingPieceM2,
 "m3/hanging-piece": patternTacticPageConfigs.hangingPieceM3,
 "m4/hanging-piece": patternTacticPageConfigs.hangingPieceM4,
 "m1/trapped-piece": patternTacticPageConfigs.trappedPieceM1,
 "m2/trapped-piece": patternTacticPageConfigs.trappedPieceM2,
 "m3/trapped-piece": patternTacticPageConfigs.trappedPieceM3,
 "m4/trapped-piece": patternTacticPageConfigs.trappedPieceM4,
 "m1/remove-the-defender": patternTacticPageConfigs.removeTheDefenderM1,
 "m2/remove-the-defender": patternTacticPageConfigs.removeTheDefenderM2,
 "m3/remove-the-defender": patternTacticPageConfigs.removeTheDefenderM3,
 "m4/remove-the-defender": patternTacticPageConfigs.removeTheDefenderM4,
 "m1/vulnerable-king": patternTacticPageConfigs.vulnerableKingM1,
 "m2/vulnerable-king": patternTacticPageConfigs.vulnerableKingM2,
 "m3/vulnerable-king": patternTacticPageConfigs.vulnerableKingM3,
 "m4/vulnerable-king": patternTacticPageConfigs.vulnerableKingM4,
 "m1/kingside-attack": patternTacticPageConfigs.kingsideAttackM1,
 "m2/kingside-attack": patternTacticPageConfigs.kingsideAttackM2,
 "m3/kingside-attack": patternTacticPageConfigs.kingsideAttackM3,
 "m4/kingside-attack": patternTacticPageConfigs.kingsideAttackM4,
 "m1/queenside-attack": patternTacticPageConfigs.queensideAttackM1,
 "m2/queenside-attack": patternTacticPageConfigs.queensideAttackM2,
 "m3/queenside-attack": patternTacticPageConfigs.queensideAttackM3,
 "m4/queenside-attack": patternTacticPageConfigs.queensideAttackM4,
 "m1/attacking-f2-f7": patternTacticPageConfigs.attackingF2F7M1,
 "m2/attacking-f2-f7": patternTacticPageConfigs.attackingF2F7M2,
 "m3/attacking-f2-f7": patternTacticPageConfigs.attackingF2F7M3,
 "m4/attacking-f2-f7": patternTacticPageConfigs.attackingF2F7M4,
 "m2/queen-sacrifice": patternTacticPageConfigs.queenSacrificeM2,
 "m3/queen-sacrifice": patternTacticPageConfigs.queenSacrificeM3,
 "m4/queen-sacrifice": patternTacticPageConfigs.queenSacrificeM4,
 "m2/rook-sacrifice": patternTacticPageConfigs.rookSacrificeM2,
 "m3/rook-sacrifice": patternTacticPageConfigs.rookSacrificeM3,
 "m4/rook-sacrifice": patternTacticPageConfigs.rookSacrificeM4,
 "m2/bishop-sacrifice": patternTacticPageConfigs.bishopSacrificeM2,
 "m3/bishop-sacrifice": patternTacticPageConfigs.bishopSacrificeM3,
 "m4/bishop-sacrifice": patternTacticPageConfigs.bishopSacrificeM4,
 "m2/knight-sacrifice": patternTacticPageConfigs.knightSacrificeM2,
 "m3/knight-sacrifice": patternTacticPageConfigs.knightSacrificeM3,
 "m4/knight-sacrifice": patternTacticPageConfigs.knightSacrificeM4,
 "m2/pawn-sacrifice": patternTacticPageConfigs.pawnSacrificeM2,
 "m3/pawn-sacrifice": patternTacticPageConfigs.pawnSacrificeM3,
 "m4/pawn-sacrifice": patternTacticPageConfigs.pawnSacrificeM4,
 "m1/clearance": patternTacticPageConfigs.clearanceM1,
 "m2/clearance": patternTacticPageConfigs.clearanceM2,
 "m3/clearance": patternTacticPageConfigs.clearanceM3,
 "m4/clearance": patternTacticPageConfigs.clearanceM4,
 "m1/diagonal-clearance": patternTacticPageConfigs.diagonalClearanceM1,
 "m1/file-clearance": patternTacticPageConfigs.fileClearanceM1,
 "m2/file-clearance": patternTacticPageConfigs.fileClearanceM2,
 "m1/rank-clearance": patternTacticPageConfigs.rankClearanceM1,
 "m2/rank-clearance": patternTacticPageConfigs.rankClearanceM2,
 "m1/clearance-sacrifice": patternTacticPageConfigs.clearanceSacrificeM1,
 "m2/clearance-sacrifice": patternTacticPageConfigs.clearanceSacrificeM2,
 "m3/clearance-sacrifice": patternTacticPageConfigs.clearanceSacrificeM3,
 "m4/clearance-sacrifice": patternTacticPageConfigs.clearanceSacrificeM4,
 "m1/interference": patternTacticPageConfigs.interferenceM1,
 "m2/interference": patternTacticPageConfigs.interferenceM2,
 "m3/interference": patternTacticPageConfigs.interferenceM3,
 "m4/interference": patternTacticPageConfigs.interferenceM4,
 "m1/interference-sacrifice": patternTacticPageConfigs.interferenceSacrificeM1,
 "m2/interference-sacrifice": patternTacticPageConfigs.interferenceSacrificeM2,
 "m3/interference-sacrifice": patternTacticPageConfigs.interferenceSacrificeM3,
 "m4/interference-sacrifice": patternTacticPageConfigs.interferenceSacrificeM4,
 "m1/queen-xray": patternTacticPageConfigs.queenXrayM1,
 "m2/queen-xray": patternTacticPageConfigs.queenXrayM2,
 "m3/queen-xray": patternTacticPageConfigs.queenXrayM3,
 "m4/queen-xray": patternTacticPageConfigs.queenXrayM4,
 "m1/rook-xray": patternTacticPageConfigs.rookXrayM1,
 "m2/rook-xray": patternTacticPageConfigs.rookXrayM2,
 "m3/rook-xray": patternTacticPageConfigs.rookXrayM3,
 "m4/rook-xray": patternTacticPageConfigs.rookXrayM4,
 "m1/bishop-xray": patternTacticPageConfigs.bishopXrayM1,
 "m2/bishop-xray": patternTacticPageConfigs.bishopXrayM2,
 "m3/bishop-xray": patternTacticPageConfigs.bishopXrayM3,
 "m4/bishop-xray": patternTacticPageConfigs.bishopXrayM4,
 "m1/promotion": patternTacticPageConfigs.promotionM1,
 "m2/promotion": patternTacticPageConfigs.promotionM2,
 "m3/promotion": patternTacticPageConfigs.promotionM3,
 "m4/promotion": patternTacticPageConfigs.promotionM4,
 "m1/underpromotion": patternTacticPageConfigs.underpromotionM1,
 "m2/underpromotion": patternTacticPageConfigs.underpromotionM2,
 "m3/underpromotion": patternTacticPageConfigs.underpromotionM3,
 "m4/underpromotion": patternTacticPageConfigs.underpromotionM4,
 "m1/knight-underpromotion": patternTacticPageConfigs.knightUnderpromotionM1,
 "m2/knight-underpromotion": patternTacticPageConfigs.knightUnderpromotionM2,
 "m3/knight-underpromotion": patternTacticPageConfigs.knightUnderpromotionM3,
 "m4/knight-underpromotion": patternTacticPageConfigs.knightUnderpromotionM4,
 "m1/en-passant": patternTacticPageConfigs.enPassantM1,
 "m2/en-passant": patternTacticPageConfigs.enPassantM2,
 "m3/en-passant": patternTacticPageConfigs.enPassantM3,
 "m4/en-passant": patternTacticPageConfigs.enPassantM4,
 "m1/zugzwang": patternTacticPageConfigs.zugzwangM1,
 "m2/zugzwang": patternTacticPageConfigs.zugzwangM2,
 "m3/zugzwang": patternTacticPageConfigs.zugzwangM3,
 "m4/zugzwang": patternTacticPageConfigs.zugzwangM4,
 "m1/zwischencheck": patternTacticPageConfigs.zwischencheckM1,
 "m1/zwischenzug": patternTacticPageConfigs.zwischenzugM1,
 "m2/zwischenzug": patternTacticPageConfigs.zwischenzugM2,
 "m3/zwischenzug": patternTacticPageConfigs.zwischenzugM3,
 "m4/zwischenzug": patternTacticPageConfigs.zwischenzugM4,
 "m1/mixed": patternTacticPageConfigs.mixedM1,
 "m2/mixed": patternTacticPageConfigs.mixedM2,
 "m3/mixed": patternTacticPageConfigs.mixedM3,
 "m4/mixed": patternTacticPageConfigs.mixedM4,
}

// Only reviewed final-v6 courses may mount a learner board. Keep historical
// definitions isolated above for migration/reference work, never as routes.
export const patternTacticConfigByRoute = generatedVerifiedFinalConfigs

export type PatternTacticPageConfigKey = keyof typeof patternTacticPageConfigs
