export const patternTacticPageConfigs = {
 defenseM1: {
 title: "Defense - Tactic in 1",
 explanationKey: "tacticDefense",
 manifestPath: "/data/pattern-tactics/defense/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/defense/m1",
 progressKey: "tactic-defense-m1",
 trainerKey: "tactic-defense-m1",
 },
 defenseM2: {
 title: "Defense - Tactic in 2",
 explanationKey: "tacticDefense",
 manifestPath: "/data/pattern-tactics/defense/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/defense/m2",
 progressKey: "tactic-defense-m2",
 trainerKey: "tactic-defense-m2",
 },
 defenseM3: {
 title: "Defense - Tactic in 3",
 explanationKey: "tacticDefense",
 manifestPath: "/data/pattern-tactics/defense/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/defense/m3",
 progressKey: "tactic-defense-m3",
 trainerKey: "tactic-defense-m3",
 },
 defenseM4: {
 title: "Defense - Tactic in 4+",
 explanationKey: "tacticDefense",
 manifestPath: "/data/pattern-tactics/defense/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/defense/m4",
 progressKey: "tactic-defense-m4",
 trainerKey: "tactic-defense-m4",
 },
 advancedPawnM1: {
 title: "Advanced Pawn - Tactic in 1",
 explanationKey: "tacticAdvancedPawn",
 manifestPath: "/data/pattern-tactics/advanced-pawn/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/advanced-pawn/m1",
 progressKey: "tactic-advanced-pawn-m1",
 trainerKey: "tactic-advanced-pawn-m1",
 },
 advancedPawnM2: {
 title: "Advanced Pawn - Tactic in 2",
 explanationKey: "tacticAdvancedPawn",
 manifestPath: "/data/pattern-tactics/advanced-pawn/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/advanced-pawn/m2",
 progressKey: "tactic-advanced-pawn-m2",
 trainerKey: "tactic-advanced-pawn-m2",
 },
 advancedPawnM3: {
 title: "Advanced Pawn - Tactic in 3",
 explanationKey: "tacticAdvancedPawn",
 manifestPath: "/data/pattern-tactics/advanced-pawn/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/advanced-pawn/m3",
 progressKey: "tactic-advanced-pawn-m3",
 trainerKey: "tactic-advanced-pawn-m3",
 },
 advancedPawnM4: {
 title: "Advanced Pawn - Tactic in 4+",
 explanationKey: "tacticAdvancedPawn",
 manifestPath: "/data/pattern-tactics/advanced-pawn/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/advanced-pawn/m4",
 progressKey: "tactic-advanced-pawn-m4",
 trainerKey: "tactic-advanced-pawn-m4",
 },
 quietMoveM1: {
 title: "Quiet Move - Tactic in 1",
 explanationKey: "tacticQuietMove",
 manifestPath: "/data/pattern-tactics/quiet-move/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/quiet-move/m1",
 progressKey: "tactic-quiet-move-m1",
 trainerKey: "tactic-quiet-move-m1",
 },
 quietMoveM2: {
 title: "Quiet Move - Tactic in 2",
 explanationKey: "tacticQuietMove",
 manifestPath: "/data/pattern-tactics/quiet-move/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/quiet-move/m2",
 progressKey: "tactic-quiet-move-m2",
 trainerKey: "tactic-quiet-move-m2",
 },
 quietMoveM3: {
 title: "Quiet Move - Tactic in 3",
 explanationKey: "tacticQuietMove",
 manifestPath: "/data/pattern-tactics/quiet-move/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/quiet-move/m3",
 progressKey: "tactic-quiet-move-m3",
 trainerKey: "tactic-quiet-move-m3",
 },
 quietMoveM4: {
 title: "Quiet Move - Tactic in 4+",
 explanationKey: "tacticQuietMove",
 manifestPath: "/data/pattern-tactics/quiet-move/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/quiet-move/m4",
 progressKey: "tactic-quiet-move-m4",
 trainerKey: "tactic-quiet-move-m4",
 },
 discoveredAttackM1: {
 title: "Discovered Attack - Tactic in 1",
 explanationKey: "tacticDiscoveredAttack",
 manifestPath: "/data/pattern-tactics/discovered-attack/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-attack/m1",
 progressKey: "tactic-discovered-attack-m1",
 trainerKey: "tactic-discovered-attack-m1",
 },
 discoveredAttackM2: {
 title: "Discovered Attack - Tactic in 2",
 explanationKey: "tacticDiscoveredAttack",
 manifestPath: "/data/pattern-tactics/discovered-attack/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-attack/m2",
 progressKey: "tactic-discovered-attack-m2",
 trainerKey: "tactic-discovered-attack-m2",
 },
 discoveredAttackM3: {
 title: "Discovered Attack - Tactic in 3",
 explanationKey: "tacticDiscoveredAttack",
 manifestPath: "/data/pattern-tactics/discovered-attack/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-attack/m3",
 progressKey: "tactic-discovered-attack-m3",
 trainerKey: "tactic-discovered-attack-m3",
 },
 discoveredAttackM4: {
 title: "Discovered Attack - Tactic in 4+",
 explanationKey: "tacticDiscoveredAttack",
 manifestPath: "/data/pattern-tactics/discovered-attack/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-attack/m4",
 progressKey: "tactic-discovered-attack-m4",
 trainerKey: "tactic-discovered-attack-m4",
 },
 discoveredCheckM1: {
 title: "Discovered Check - Tactic in 1",
 explanationKey: "tacticDiscoveredCheck",
 manifestPath: "/data/pattern-tactics/discovered-check/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-check/m1",
 progressKey: "tactic-discovered-check-m1",
 trainerKey: "tactic-discovered-check-m1",
 },
 discoveredCheckM2: {
 title: "Discovered Check - Tactic in 2",
 explanationKey: "tacticDiscoveredCheck",
 manifestPath: "/data/pattern-tactics/discovered-check/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-check/m2",
 progressKey: "tactic-discovered-check-m2",
 trainerKey: "tactic-discovered-check-m2",
 },
 discoveredCheckM3: {
 title: "Discovered Check - Tactic in 3",
 explanationKey: "tacticDiscoveredCheck",
 manifestPath: "/data/pattern-tactics/discovered-check/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-check/m3",
 progressKey: "tactic-discovered-check-m3",
 trainerKey: "tactic-discovered-check-m3",
 },
 discoveredCheckM4: {
 title: "Discovered Check - Tactic in 4+",
 explanationKey: "tacticDiscoveredCheck",
 manifestPath: "/data/pattern-tactics/discovered-check/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/discovered-check/m4",
 progressKey: "tactic-discovered-check-m4",
 trainerKey: "tactic-discovered-check-m4",
 },
 doubleCheckM1: {
 title: "Double Check - Tactic in 1",
 explanationKey: "tacticDoubleCheck",
 manifestPath: "/data/pattern-tactics/double-check/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/double-check/m1",
 progressKey: "tactic-double-check-m1",
 trainerKey: "tactic-double-check-m1",
 },
 doubleCheckM2: {
 title: "Double Check - Tactic in 2",
 explanationKey: "tacticDoubleCheck",
 manifestPath: "/data/pattern-tactics/double-check/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/double-check/m2",
 progressKey: "tactic-double-check-m2",
 trainerKey: "tactic-double-check-m2",
 },
 doubleCheckM3: {
 title: "Double Check - Tactic in 3",
 explanationKey: "tacticDoubleCheck",
 manifestPath: "/data/pattern-tactics/double-check/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/double-check/m3",
 progressKey: "tactic-double-check-m3",
 trainerKey: "tactic-double-check-m3",
 },
 doubleCheckM4: {
 title: "Double Check - Tactic in 4+",
 explanationKey: "tacticDoubleCheck",
 manifestPath: "/data/pattern-tactics/double-check/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/double-check/m4",
 progressKey: "tactic-double-check-m4",
 trainerKey: "tactic-double-check-m4",
 },
 forkKnightM1: {
 title: "Knight Fork / Double Attack - Tactic in 1",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/knight-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-fork/m1",
 progressKey: "tactic-fork-knight-m1",
 trainerKey: "tactic-fork-knight-m1",
 },
 forkKnightM2: {
 title: "Knight Fork / Double Attack - Tactic in 2",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/knight-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-fork/m2",
 progressKey: "tactic-fork-knight-m2",
 trainerKey: "tactic-fork-knight-m2",
 },
 forkKnightM3: {
 title: "Knight Fork / Double Attack - Tactic in 3",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/knight-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-fork/m3",
 progressKey: "tactic-fork-knight-m3",
 trainerKey: "tactic-fork-knight-m3",
 },
 forkKnightM4: {
 title: "Knight Fork / Double Attack - Tactic in 4+",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/knight-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-fork/m4",
 progressKey: "tactic-fork-knight-m4",
 trainerKey: "tactic-fork-knight-m4",
 },
 forkQueenM1: {
 title: "Queen Fork / Double Attack - Tactic in 1",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/queen-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-fork/m1",
 progressKey: "tactic-fork-queen-m1",
 trainerKey: "tactic-fork-queen-m1",
 },
 forkQueenM2: {
 title: "Queen Fork / Double Attack - Tactic in 2",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/queen-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-fork/m2",
 progressKey: "tactic-fork-queen-m2",
 trainerKey: "tactic-fork-queen-m2",
 },
 forkQueenM3: {
 title: "Queen Fork / Double Attack - Tactic in 3",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/queen-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-fork/m3",
 progressKey: "tactic-fork-queen-m3",
 trainerKey: "tactic-fork-queen-m3",
 },
 forkQueenM4: {
 title: "Queen Fork / Double Attack - Tactic in 4+",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/queen-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-fork/m4",
 progressKey: "tactic-fork-queen-m4",
 trainerKey: "tactic-fork-queen-m4",
 },
 forkRookM1: {
 title: "Rook Fork / Double Attack - Tactic in 1",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/rook-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-fork/m1",
 progressKey: "tactic-fork-rook-m1",
 trainerKey: "tactic-fork-rook-m1",
 },
 forkRookM2: {
 title: "Rook Fork / Double Attack - Tactic in 2",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/rook-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-fork/m2",
 progressKey: "tactic-fork-rook-m2",
 trainerKey: "tactic-fork-rook-m2",
 },
 forkRookM3: {
 title: "Rook Fork / Double Attack - Tactic in 3",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/rook-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-fork/m3",
 progressKey: "tactic-fork-rook-m3",
 trainerKey: "tactic-fork-rook-m3",
 },
 forkRookM4: {
 title: "Rook Fork / Double Attack - Tactic in 4+",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/rook-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-fork/m4",
 progressKey: "tactic-fork-rook-m4",
 trainerKey: "tactic-fork-rook-m4",
 },
 forkBishopM1: {
 title: "Bishop Fork / Double Attack - Tactic in 1",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/bishop-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-fork/m1",
 progressKey: "tactic-fork-bishop-m1",
 trainerKey: "tactic-fork-bishop-m1",
 },
 forkBishopM2: {
 title: "Bishop Fork / Double Attack - Tactic in 2",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/bishop-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-fork/m2",
 progressKey: "tactic-fork-bishop-m2",
 trainerKey: "tactic-fork-bishop-m2",
 },
 forkBishopM3: {
 title: "Bishop Fork / Double Attack - Tactic in 3",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/bishop-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-fork/m3",
 progressKey: "tactic-fork-bishop-m3",
 trainerKey: "tactic-fork-bishop-m3",
 },
 forkBishopM4: {
 title: "Bishop Fork / Double Attack - Tactic in 4+",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/bishop-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-fork/m4",
 progressKey: "tactic-fork-bishop-m4",
 trainerKey: "tactic-fork-bishop-m4",
 },
 forkPawnM1: {
 title: "Pawn Fork / Double Attack - Tactic in 1",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/pawn-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-fork/m1",
 progressKey: "tactic-fork-pawn-m1",
 trainerKey: "tactic-fork-pawn-m1",
 },
 forkPawnM2: {
 title: "Pawn Fork / Double Attack - Tactic in 2",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/pawn-fork/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-fork/m2",
 progressKey: "tactic-fork-pawn-m2",
 trainerKey: "tactic-fork-pawn-m2",
 },
 forkPawnM3: {
 title: "Pawn Fork / Double Attack - Tactic in 3",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/pawn-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-fork/m3",
 progressKey: "tactic-fork-pawn-m3",
 trainerKey: "tactic-fork-pawn-m3",
 },
 forkPawnM4: {
 title: "Pawn Fork / Double Attack - Tactic in 4+",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/pawn-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-fork/m4",
 progressKey: "tactic-fork-pawn-m4",
 trainerKey: "tactic-fork-pawn-m4",
 },
 forkKingM1: {
 title: "King Fork / Double Attack - Tactic in 1",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/king-fork/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-fork/m1",
 progressKey: "tactic-fork-king-m1",
 trainerKey: "tactic-fork-king-m1",
 },
 forkKingM3: {
 title: "King Fork / Double Attack - Tactic in 3",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/king-fork/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-fork/m3",
 progressKey: "tactic-fork-king-m3",
 trainerKey: "tactic-fork-king-m3",
 },
 forkKingM4: {
 title: "King Fork / Double Attack - Tactic in 4+",
 explanationKey: "tacticForkDoubleAttack",
 manifestPath: "/data/pattern-tactics/king-fork/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-fork/m4",
 progressKey: "tactic-fork-king-m4",
 trainerKey: "tactic-fork-king-m4",
 },
 pinRookM1: {
 title: "Rook Pin - Tactic in 1",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/rook-pin/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-pin/m1",
 progressKey: "tactic-pin-rook-m1",
 trainerKey: "tactic-pin-rook-m1",
 },
 pinRookM2: {
 title: "Rook Pin - Tactic in 2",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/rook-pin/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-pin/m2",
 progressKey: "tactic-pin-rook-m2",
 trainerKey: "tactic-pin-rook-m2",
 },
 pinRookM3: {
 title: "Rook Pin - Tactic in 3",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/rook-pin/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-pin/m3",
 progressKey: "tactic-pin-rook-m3",
 trainerKey: "tactic-pin-rook-m3",
 },
 pinRookM4: {
 title: "Rook Pin - Tactic in 4+",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/rook-pin/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-pin/m4",
 progressKey: "tactic-pin-rook-m4",
 trainerKey: "tactic-pin-rook-m4",
 },
 pinQueenM1: {
 title: "Queen Pin - Tactic in 1",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/queen-pin/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-pin/m1",
 progressKey: "tactic-pin-queen-m1",
 trainerKey: "tactic-pin-queen-m1",
 },
 pinQueenM2: {
 title: "Queen Pin - Tactic in 2",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/queen-pin/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-pin/m2",
 progressKey: "tactic-pin-queen-m2",
 trainerKey: "tactic-pin-queen-m2",
 },
 pinQueenM3: {
 title: "Queen Pin - Tactic in 3",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/queen-pin/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-pin/m3",
 progressKey: "tactic-pin-queen-m3",
 trainerKey: "tactic-pin-queen-m3",
 },
 pinQueenM4: {
 title: "Queen Pin - Tactic in 4+",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/queen-pin/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-pin/m4",
 progressKey: "tactic-pin-queen-m4",
 trainerKey: "tactic-pin-queen-m4",
 },
 pinBishopM1: {
 title: "Bishop Pin - Tactic in 1",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/bishop-pin/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-pin/m1",
 progressKey: "tactic-pin-bishop-m1",
 trainerKey: "tactic-pin-bishop-m1",
 },
 pinBishopM2: {
 title: "Bishop Pin - Tactic in 2",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/bishop-pin/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-pin/m2",
 progressKey: "tactic-pin-bishop-m2",
 trainerKey: "tactic-pin-bishop-m2",
 },
 pinBishopM3: {
 title: "Bishop Pin - Tactic in 3",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/bishop-pin/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-pin/m3",
 progressKey: "tactic-pin-bishop-m3",
 trainerKey: "tactic-pin-bishop-m3",
 },
 pinBishopM4: {
 title: "Bishop Pin - Tactic in 4+",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/bishop-pin/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-pin/m4",
 progressKey: "tactic-pin-bishop-m4",
 trainerKey: "tactic-pin-bishop-m4",
 },
 pinOtherM1: {
 title: "Other Pin - Tactic in 1",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/other-pin/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-pin/m1",
 progressKey: "tactic-pin-other-m1",
 trainerKey: "tactic-pin-other-m1",
 },
 pinOtherM2: {
 title: "Other Pin - Tactic in 2",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/other-pin/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-pin/m2",
 progressKey: "tactic-pin-other-m2",
 trainerKey: "tactic-pin-other-m2",
 },
 pinOtherM3: {
 title: "Other Pin - Tactic in 3",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/other-pin/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-pin/m3",
 progressKey: "tactic-pin-other-m3",
 trainerKey: "tactic-pin-other-m3",
 },
 pinOtherM4: {
 title: "Other Pin - Tactic in 4+",
 explanationKey: "tacticPin",
 manifestPath: "/data/pattern-tactics/other-pin/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-pin/m4",
 progressKey: "tactic-pin-other-m4",
 trainerKey: "tactic-pin-other-m4",
 },
 skewerRookM1: {
 title: "Rook Skewer - Tactic in 1",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/rook-skewer/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-skewer/m1",
 progressKey: "tactic-skewer-rook-m1",
 trainerKey: "tactic-skewer-rook-m1",
 },
 skewerRookM2: {
 title: "Rook Skewer - Tactic in 2",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/rook-skewer/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-skewer/m2",
 progressKey: "tactic-skewer-rook-m2",
 trainerKey: "tactic-skewer-rook-m2",
 },
 skewerRookM3: {
 title: "Rook Skewer - Tactic in 3",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/rook-skewer/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-skewer/m3",
 progressKey: "tactic-skewer-rook-m3",
 trainerKey: "tactic-skewer-rook-m3",
 },
 skewerRookM4: {
 title: "Rook Skewer - Tactic in 4+",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/rook-skewer/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-skewer/m4",
 progressKey: "tactic-skewer-rook-m4",
 trainerKey: "tactic-skewer-rook-m4",
 },
 skewerQueenM1: {
 title: "Queen Skewer - Tactic in 1",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/queen-skewer/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-skewer/m1",
 progressKey: "tactic-skewer-queen-m1",
 trainerKey: "tactic-skewer-queen-m1",
 },
 skewerQueenM2: {
 title: "Queen Skewer - Tactic in 2",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/queen-skewer/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-skewer/m2",
 progressKey: "tactic-skewer-queen-m2",
 trainerKey: "tactic-skewer-queen-m2",
 },
 skewerQueenM3: {
 title: "Queen Skewer - Tactic in 3",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/queen-skewer/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-skewer/m3",
 progressKey: "tactic-skewer-queen-m3",
 trainerKey: "tactic-skewer-queen-m3",
 },
 skewerQueenM4: {
 title: "Queen Skewer - Tactic in 4+",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/queen-skewer/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-skewer/m4",
 progressKey: "tactic-skewer-queen-m4",
 trainerKey: "tactic-skewer-queen-m4",
 },
 skewerBishopM1: {
 title: "Bishop Skewer - Tactic in 1",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/bishop-skewer/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-skewer/m1",
 progressKey: "tactic-skewer-bishop-m1",
 trainerKey: "tactic-skewer-bishop-m1",
 },
 skewerBishopM2: {
 title: "Bishop Skewer - Tactic in 2",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/bishop-skewer/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-skewer/m2",
 progressKey: "tactic-skewer-bishop-m2",
 trainerKey: "tactic-skewer-bishop-m2",
 },
 skewerBishopM3: {
 title: "Bishop Skewer - Tactic in 3",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/bishop-skewer/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-skewer/m3",
 progressKey: "tactic-skewer-bishop-m3",
 trainerKey: "tactic-skewer-bishop-m3",
 },
 skewerBishopM4: {
 title: "Bishop Skewer - Tactic in 4+",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/bishop-skewer/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-skewer/m4",
 progressKey: "tactic-skewer-bishop-m4",
 trainerKey: "tactic-skewer-bishop-m4",
 },
 skewerOtherM1: {
 title: "Other Skewer - Tactic in 1",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/other-skewer/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-skewer/m1",
 progressKey: "tactic-skewer-other-m1",
 trainerKey: "tactic-skewer-other-m1",
 },
 skewerOtherM2: {
 title: "Other Skewer - Tactic in 2",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/other-skewer/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-skewer/m2",
 progressKey: "tactic-skewer-other-m2",
 trainerKey: "tactic-skewer-other-m2",
 },
 skewerOtherM3: {
 title: "Other Skewer - Tactic in 3",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/other-skewer/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-skewer/m3",
 progressKey: "tactic-skewer-other-m3",
 trainerKey: "tactic-skewer-other-m3",
 },
 skewerOtherM4: {
 title: "Other Skewer - Tactic in 4+",
 explanationKey: "tacticSkewer",
 manifestPath: "/data/pattern-tactics/other-skewer/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-skewer/m4",
 progressKey: "tactic-skewer-other-m4",
 trainerKey: "tactic-skewer-other-m4",
 },
 decoyAttractionM1: {
 title: "Decoy / Attraction - Tactic in 1",
 explanationKey: "tacticDecoyAttraction",
 manifestPath: "/data/pattern-tactics/decoy-attraction/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-attraction/m1",
 progressKey: "tactic-decoy-attraction-m1",
 trainerKey: "tactic-decoy-attraction-m1",
 },
 decoyAttractionM2: {
 title: "Decoy / Attraction - Tactic in 2",
 explanationKey: "tacticDecoyAttraction",
 manifestPath: "/data/pattern-tactics/decoy-attraction/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-attraction/m2",
 progressKey: "tactic-decoy-attraction-m2",
 trainerKey: "tactic-decoy-attraction-m2",
 },
 decoyAttractionM3: {
 title: "Decoy / Attraction - Tactic in 3",
 explanationKey: "tacticDecoyAttraction",
 manifestPath: "/data/pattern-tactics/decoy-attraction/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-attraction/m3",
 progressKey: "tactic-decoy-attraction-m3",
 trainerKey: "tactic-decoy-attraction-m3",
 },
 decoyAttractionM4: {
 title: "Decoy / Attraction - Tactic in 4+",
 explanationKey: "tacticDecoyAttraction",
 manifestPath: "/data/pattern-tactics/decoy-attraction/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-attraction/m4",
 progressKey: "tactic-decoy-attraction-m4",
 trainerKey: "tactic-decoy-attraction-m4",
 },
 deflectionM1: {
 title: "Deflection - Tactic in 1",
 explanationKey: "tacticDeflection",
 manifestPath: "/data/pattern-tactics/deflection/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/deflection/m1",
 progressKey: "tactic-deflection-m1",
 trainerKey: "tactic-deflection-m1",
 },
 deflectionM2: {
 title: "Deflection - Tactic in 2",
 explanationKey: "tacticDeflection",
 manifestPath: "/data/pattern-tactics/deflection/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/deflection/m2",
 progressKey: "tactic-deflection-m2",
 trainerKey: "tactic-deflection-m2",
 },
 deflectionM3: {
 title: "Deflection - Tactic in 3",
 explanationKey: "tacticDeflection",
 manifestPath: "/data/pattern-tactics/deflection/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/deflection/m3",
 progressKey: "tactic-deflection-m3",
 trainerKey: "tactic-deflection-m3",
 },
 deflectionM4: {
 title: "Deflection - Tactic in 4+",
 explanationKey: "tacticDeflection",
 manifestPath: "/data/pattern-tactics/deflection/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/deflection/m4",
 progressKey: "tactic-deflection-m4",
 trainerKey: "tactic-deflection-m4",
 },
 decoyDeflectionCombinedM1: {
 title: "Decoy + Deflection - Tactic in 1",
 explanationKey: "tacticDecoyDeflection",
 manifestPath: "/data/pattern-tactics/decoy-deflection/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-deflection/m1",
 progressKey: "tactic-decoy-deflection-combined-m1",
 trainerKey: "tactic-decoy-deflection-combined-m1",
 },
 decoyDeflectionCombinedM2: {
 title: "Decoy + Deflection - Tactic in 2",
 explanationKey: "tacticDecoyDeflection",
 manifestPath: "/data/pattern-tactics/decoy-deflection/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-deflection/m2",
 progressKey: "tactic-decoy-deflection-combined-m2",
 trainerKey: "tactic-decoy-deflection-combined-m2",
 },
 decoyDeflectionCombinedM3: {
 title: "Decoy + Deflection - Tactic in 3",
 explanationKey: "tacticDecoyDeflection",
 manifestPath: "/data/pattern-tactics/decoy-deflection/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-deflection/m3",
 progressKey: "tactic-decoy-deflection-combined-m3",
 trainerKey: "tactic-decoy-deflection-combined-m3",
 },
 decoyDeflectionCombinedM4: {
 title: "Decoy + Deflection - Tactic in 4+",
 explanationKey: "tacticDecoyDeflection",
 manifestPath: "/data/pattern-tactics/decoy-deflection/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/decoy-deflection/m4",
 progressKey: "tactic-decoy-deflection-combined-m4",
 trainerKey: "tactic-decoy-deflection-combined-m4",
 },
 hangingPieceM1: {
 title: "Hanging Piece - Tactic in 1",
 explanationKey: "tacticHangingPiece",
 manifestPath: "/data/pattern-tactics/hanging-piece/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/hanging-piece/m1",
 progressKey: "tactic-hanging-piece-m1",
 trainerKey: "tactic-hanging-piece-m1",
 },
 hangingPieceM2: {
 title: "Hanging Piece - Tactic in 2",
 explanationKey: "tacticHangingPiece",
 manifestPath: "/data/pattern-tactics/hanging-piece/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/hanging-piece/m2",
 progressKey: "tactic-hanging-piece-m2",
 trainerKey: "tactic-hanging-piece-m2",
 },
 hangingPieceM3: {
 title: "Hanging Piece - Tactic in 3",
 explanationKey: "tacticHangingPiece",
 manifestPath: "/data/pattern-tactics/hanging-piece/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/hanging-piece/m3",
 progressKey: "tactic-hanging-piece-m3",
 trainerKey: "tactic-hanging-piece-m3",
 },
 hangingPieceM4: {
 title: "Hanging Piece - Tactic in 4+",
 explanationKey: "tacticHangingPiece",
 manifestPath: "/data/pattern-tactics/hanging-piece/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/hanging-piece/m4",
 progressKey: "tactic-hanging-piece-m4",
 trainerKey: "tactic-hanging-piece-m4",
 },
 trappedPieceM1: {
 title: "Trapped Piece - Tactic in 1",
 explanationKey: "tacticTrappedPiece",
 manifestPath: "/data/pattern-tactics/trapped-piece/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/trapped-piece/m1",
 progressKey: "tactic-trapped-piece-m1",
 trainerKey: "tactic-trapped-piece-m1",
 },
 trappedPieceM2: {
 title: "Trapped Piece - Tactic in 2",
 explanationKey: "tacticTrappedPiece",
 manifestPath: "/data/pattern-tactics/trapped-piece/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/trapped-piece/m2",
 progressKey: "tactic-trapped-piece-m2",
 trainerKey: "tactic-trapped-piece-m2",
 },
 trappedPieceM3: {
 title: "Trapped Piece - Tactic in 3",
 explanationKey: "tacticTrappedPiece",
 manifestPath: "/data/pattern-tactics/trapped-piece/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/trapped-piece/m3",
 progressKey: "tactic-trapped-piece-m3",
 trainerKey: "tactic-trapped-piece-m3",
 },
 trappedPieceM4: {
 title: "Trapped Piece - Tactic in 4+",
 explanationKey: "tacticTrappedPiece",
 manifestPath: "/data/pattern-tactics/trapped-piece/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/trapped-piece/m4",
 progressKey: "tactic-trapped-piece-m4",
 trainerKey: "tactic-trapped-piece-m4",
 },
 removeTheDefenderM1: {
 title: "Remove the Defender - Tactic in 1",
 explanationKey: "tacticRemoveDefender",
 manifestPath: "/data/pattern-tactics/remove-the-defender/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/remove-the-defender/m1",
 progressKey: "tactic-remove-the-defender-m1",
 trainerKey: "tactic-remove-the-defender-m1",
 },
 removeTheDefenderM2: {
 title: "Remove the Defender - Tactic in 2",
 explanationKey: "tacticRemoveDefender",
 manifestPath: "/data/pattern-tactics/remove-the-defender/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/remove-the-defender/m2",
 progressKey: "tactic-remove-the-defender-m2",
 trainerKey: "tactic-remove-the-defender-m2",
 },
 removeTheDefenderM3: {
 title: "Remove the Defender - Tactic in 3",
 explanationKey: "tacticRemoveDefender",
 manifestPath: "/data/pattern-tactics/remove-the-defender/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/remove-the-defender/m3",
 progressKey: "tactic-remove-the-defender-m3",
 trainerKey: "tactic-remove-the-defender-m3",
 },
 removeTheDefenderM4: {
 title: "Remove the Defender - Tactic in 4+",
 explanationKey: "tacticRemoveDefender",
 manifestPath: "/data/pattern-tactics/remove-the-defender/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/remove-the-defender/m4",
 progressKey: "tactic-remove-the-defender-m4",
 trainerKey: "tactic-remove-the-defender-m4",
 },
 vulnerableKingM1: {
 title: "Vulnerable / Exposed King - Tactic in 1",
 explanationKey: "tacticVulnerableKing",
 manifestPath: "/data/pattern-tactics/vulnerable-king/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/vulnerable-king/m1",
 progressKey: "tactic-vulnerable-king-m1",
 trainerKey: "tactic-vulnerable-king-m1",
 },
 vulnerableKingM3: {
 title: "Vulnerable / Exposed King - Tactic in 3",
 explanationKey: "tacticVulnerableKing",
 manifestPath: "/data/pattern-tactics/vulnerable-king/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/vulnerable-king/m3",
 progressKey: "tactic-vulnerable-king-m3",
 trainerKey: "tactic-vulnerable-king-m3",
 },
 vulnerableKingM4: {
 title: "Vulnerable / Exposed King - Tactic in 4+",
 explanationKey: "tacticVulnerableKing",
 manifestPath: "/data/pattern-tactics/vulnerable-king/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/vulnerable-king/m4",
 progressKey: "tactic-vulnerable-king-m4",
 trainerKey: "tactic-vulnerable-king-m4",
 },
 kingsideAttackM1: {
 title: "Kingside Attack - Tactic in 1",
 explanationKey: "tacticKingsideAttack",
 manifestPath: "/data/pattern-tactics/kingside-attack/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/kingside-attack/m1",
 progressKey: "tactic-kingside-attack-m1",
 trainerKey: "tactic-kingside-attack-m1",
 },
 kingsideAttackM2: {
 title: "Kingside Attack - Tactic in 2",
 explanationKey: "tacticKingsideAttack",
 manifestPath: "/data/pattern-tactics/kingside-attack/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/kingside-attack/m2",
 progressKey: "tactic-kingside-attack-m2",
 trainerKey: "tactic-kingside-attack-m2",
 },
 kingsideAttackM3: {
 title: "Kingside Attack - Tactic in 3",
 explanationKey: "tacticKingsideAttack",
 manifestPath: "/data/pattern-tactics/kingside-attack/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/kingside-attack/m3",
 progressKey: "tactic-kingside-attack-m3",
 trainerKey: "tactic-kingside-attack-m3",
 },
 kingsideAttackM4: {
 title: "Kingside Attack - Tactic in 4+",
 explanationKey: "tacticKingsideAttack",
 manifestPath: "/data/pattern-tactics/kingside-attack/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/kingside-attack/m4",
 progressKey: "tactic-kingside-attack-m4",
 trainerKey: "tactic-kingside-attack-m4",
 },
 queensideAttackM1: {
 title: "Queenside Attack - Tactic in 1",
 explanationKey: "tacticQueensideAttack",
 manifestPath: "/data/pattern-tactics/queenside-attack/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queenside-attack/m1",
 progressKey: "tactic-queenside-attack-m1",
 trainerKey: "tactic-queenside-attack-m1",
 },
 queensideAttackM2: {
 title: "Queenside Attack - Tactic in 2",
 explanationKey: "tacticQueensideAttack",
 manifestPath: "/data/pattern-tactics/queenside-attack/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queenside-attack/m2",
 progressKey: "tactic-queenside-attack-m2",
 trainerKey: "tactic-queenside-attack-m2",
 },
 queensideAttackM3: {
 title: "Queenside Attack - Tactic in 3",
 explanationKey: "tacticQueensideAttack",
 manifestPath: "/data/pattern-tactics/queenside-attack/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queenside-attack/m3",
 progressKey: "tactic-queenside-attack-m3",
 trainerKey: "tactic-queenside-attack-m3",
 },
 queensideAttackM4: {
 title: "Queenside Attack - Tactic in 4+",
 explanationKey: "tacticQueensideAttack",
 manifestPath: "/data/pattern-tactics/queenside-attack/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queenside-attack/m4",
 progressKey: "tactic-queenside-attack-m4",
 trainerKey: "tactic-queenside-attack-m4",
 },
 attackingF2F7M1: {
 title: "Attacking f2/f7 - Tactic in 1",
 explanationKey: "tacticAttackingF2F7",
 manifestPath: "/data/pattern-tactics/attacking-f2-f7/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/attacking-f2-f7/m1",
 progressKey: "tactic-attacking-f2-f7-m1",
 trainerKey: "tactic-attacking-f2-f7-m1",
 },
 attackingF2F7M2: {
 title: "Attacking f2/f7 - Tactic in 2",
 explanationKey: "tacticAttackingF2F7",
 manifestPath: "/data/pattern-tactics/attacking-f2-f7/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/attacking-f2-f7/m2",
 progressKey: "tactic-attacking-f2-f7-m2",
 trainerKey: "tactic-attacking-f2-f7-m2",
 },
 attackingF2F7M3: {
 title: "Attacking f2/f7 - Tactic in 3",
 explanationKey: "tacticAttackingF2F7",
 manifestPath: "/data/pattern-tactics/attacking-f2-f7/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/attacking-f2-f7/m3",
 progressKey: "tactic-attacking-f2-f7-m3",
 trainerKey: "tactic-attacking-f2-f7-m3",
 },
 attackingF2F7M4: {
 title: "Attacking f2/f7 - Tactic in 4+",
 explanationKey: "tacticAttackingF2F7",
 manifestPath: "/data/pattern-tactics/attacking-f2-f7/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/attacking-f2-f7/m4",
 progressKey: "tactic-attacking-f2-f7-m4",
 trainerKey: "tactic-attacking-f2-f7-m4",
 },
 sacrificeQueenM1: {
 title: "Queen Sacrifice - Tactic in 1",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/queen-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-sacrifice/m1",
 progressKey: "tactic-sacrifice-queen-m1",
 trainerKey: "tactic-sacrifice-queen-m1",
 },
 sacrificeQueenM2: {
 title: "Queen Sacrifice - Tactic in 2",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/queen-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-sacrifice/m2",
 progressKey: "tactic-sacrifice-queen-m2",
 trainerKey: "tactic-sacrifice-queen-m2",
 },
 sacrificeQueenM3: {
 title: "Queen Sacrifice - Tactic in 3",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/queen-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-sacrifice/m3",
 progressKey: "tactic-sacrifice-queen-m3",
 trainerKey: "tactic-sacrifice-queen-m3",
 },
 sacrificeQueenM4: {
 title: "Queen Sacrifice - Tactic in 4+",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/queen-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-sacrifice/m4",
 progressKey: "tactic-sacrifice-queen-m4",
 trainerKey: "tactic-sacrifice-queen-m4",
 },
 sacrificeRookM1: {
 title: "Rook Sacrifice - Tactic in 1",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/rook-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-sacrifice/m1",
 progressKey: "tactic-sacrifice-rook-m1",
 trainerKey: "tactic-sacrifice-rook-m1",
 },
 sacrificeRookM2: {
 title: "Rook Sacrifice - Tactic in 2",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/rook-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-sacrifice/m2",
 progressKey: "tactic-sacrifice-rook-m2",
 trainerKey: "tactic-sacrifice-rook-m2",
 },
 sacrificeRookM3: {
 title: "Rook Sacrifice - Tactic in 3",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/rook-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-sacrifice/m3",
 progressKey: "tactic-sacrifice-rook-m3",
 trainerKey: "tactic-sacrifice-rook-m3",
 },
 sacrificeRookM4: {
 title: "Rook Sacrifice - Tactic in 4+",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/rook-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-sacrifice/m4",
 progressKey: "tactic-sacrifice-rook-m4",
 trainerKey: "tactic-sacrifice-rook-m4",
 },
 sacrificeBishopM1: {
 title: "Bishop Sacrifice - Tactic in 1",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/bishop-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-sacrifice/m1",
 progressKey: "tactic-sacrifice-bishop-m1",
 trainerKey: "tactic-sacrifice-bishop-m1",
 },
 sacrificeBishopM2: {
 title: "Bishop Sacrifice - Tactic in 2",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/bishop-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-sacrifice/m2",
 progressKey: "tactic-sacrifice-bishop-m2",
 trainerKey: "tactic-sacrifice-bishop-m2",
 },
 sacrificeBishopM3: {
 title: "Bishop Sacrifice - Tactic in 3",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/bishop-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-sacrifice/m3",
 progressKey: "tactic-sacrifice-bishop-m3",
 trainerKey: "tactic-sacrifice-bishop-m3",
 },
 sacrificeBishopM4: {
 title: "Bishop Sacrifice - Tactic in 4+",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/bishop-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-sacrifice/m4",
 progressKey: "tactic-sacrifice-bishop-m4",
 trainerKey: "tactic-sacrifice-bishop-m4",
 },
 sacrificeKnightM1: {
 title: "Knight Sacrifice - Tactic in 1",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/knight-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-sacrifice/m1",
 progressKey: "tactic-sacrifice-knight-m1",
 trainerKey: "tactic-sacrifice-knight-m1",
 },
 sacrificeKnightM2: {
 title: "Knight Sacrifice - Tactic in 2",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/knight-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-sacrifice/m2",
 progressKey: "tactic-sacrifice-knight-m2",
 trainerKey: "tactic-sacrifice-knight-m2",
 },
 sacrificeKnightM3: {
 title: "Knight Sacrifice - Tactic in 3",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/knight-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-sacrifice/m3",
 progressKey: "tactic-sacrifice-knight-m3",
 trainerKey: "tactic-sacrifice-knight-m3",
 },
 sacrificeKnightM4: {
 title: "Knight Sacrifice - Tactic in 4+",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/knight-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-sacrifice/m4",
 progressKey: "tactic-sacrifice-knight-m4",
 trainerKey: "tactic-sacrifice-knight-m4",
 },
 sacrificePawnM1: {
 title: "Pawn Sacrifice - Tactic in 1",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/pawn-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-sacrifice/m1",
 progressKey: "tactic-sacrifice-pawn-m1",
 trainerKey: "tactic-sacrifice-pawn-m1",
 },
 sacrificePawnM2: {
 title: "Pawn Sacrifice - Tactic in 2",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/pawn-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-sacrifice/m2",
 progressKey: "tactic-sacrifice-pawn-m2",
 trainerKey: "tactic-sacrifice-pawn-m2",
 },
 sacrificePawnM3: {
 title: "Pawn Sacrifice - Tactic in 3",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/pawn-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-sacrifice/m3",
 progressKey: "tactic-sacrifice-pawn-m3",
 trainerKey: "tactic-sacrifice-pawn-m3",
 },
 sacrificePawnM4: {
 title: "Pawn Sacrifice - Tactic in 4+",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/pawn-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/pawn-sacrifice/m4",
 progressKey: "tactic-sacrifice-pawn-m4",
 trainerKey: "tactic-sacrifice-pawn-m4",
 },
 sacrificeKingM1: {
 title: "King Sacrifice - Tactic in 1",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/king-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-sacrifice/m1",
 progressKey: "tactic-sacrifice-king-m1",
 trainerKey: "tactic-sacrifice-king-m1",
 },
 sacrificeKingM2: {
 title: "King Sacrifice - Tactic in 2",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/king-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-sacrifice/m2",
 progressKey: "tactic-sacrifice-king-m2",
 trainerKey: "tactic-sacrifice-king-m2",
 },
 sacrificeKingM3: {
 title: "King Sacrifice - Tactic in 3",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/king-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-sacrifice/m3",
 progressKey: "tactic-sacrifice-king-m3",
 trainerKey: "tactic-sacrifice-king-m3",
 },
 sacrificeKingM4: {
 title: "King Sacrifice - Tactic in 4+",
 explanationKey: "tacticSacrifice",
 manifestPath: "/data/pattern-tactics/king-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/king-sacrifice/m4",
 progressKey: "tactic-sacrifice-king-m4",
 trainerKey: "tactic-sacrifice-king-m4",
 },
 clearanceM1: {
 title: "Clearance - Tactic in 1",
 explanationKey: "tacticClearance",
 manifestPath: "/data/pattern-tactics/clearance/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance/m1",
 progressKey: "tactic-clearance-m1",
 trainerKey: "tactic-clearance-m1",
 },
 clearanceM2: {
 title: "Clearance - Tactic in 2",
 explanationKey: "tacticClearance",
 manifestPath: "/data/pattern-tactics/clearance/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance/m2",
 progressKey: "tactic-clearance-m2",
 trainerKey: "tactic-clearance-m2",
 },
 clearanceM3: {
 title: "Clearance - Tactic in 3",
 explanationKey: "tacticClearance",
 manifestPath: "/data/pattern-tactics/clearance/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance/m3",
 progressKey: "tactic-clearance-m3",
 trainerKey: "tactic-clearance-m3",
 },
 clearanceM4: {
 title: "Clearance - Tactic in 4+",
 explanationKey: "tacticClearance",
 manifestPath: "/data/pattern-tactics/clearance/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance/m4",
 progressKey: "tactic-clearance-m4",
 trainerKey: "tactic-clearance-m4",
 },
 clearanceSacrificeM1: {
 title: "Clearance Sacrifice - Tactic in 1",
 explanationKey: "tacticClearanceSacrifice",
 manifestPath: "/data/pattern-tactics/clearance-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance-sacrifice/m1",
 progressKey: "tactic-clearance-sacrifice-m1",
 trainerKey: "tactic-clearance-sacrifice-m1",
 },
 clearanceSacrificeM2: {
 title: "Clearance Sacrifice - Tactic in 2",
 explanationKey: "tacticClearanceSacrifice",
 manifestPath: "/data/pattern-tactics/clearance-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance-sacrifice/m2",
 progressKey: "tactic-clearance-sacrifice-m2",
 trainerKey: "tactic-clearance-sacrifice-m2",
 },
 clearanceSacrificeM3: {
 title: "Clearance Sacrifice - Tactic in 3",
 explanationKey: "tacticClearanceSacrifice",
 manifestPath: "/data/pattern-tactics/clearance-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance-sacrifice/m3",
 progressKey: "tactic-clearance-sacrifice-m3",
 trainerKey: "tactic-clearance-sacrifice-m3",
 },
 clearanceSacrificeM4: {
 title: "Clearance Sacrifice - Tactic in 4+",
 explanationKey: "tacticClearanceSacrifice",
 manifestPath: "/data/pattern-tactics/clearance-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/clearance-sacrifice/m4",
 progressKey: "tactic-clearance-sacrifice-m4",
 trainerKey: "tactic-clearance-sacrifice-m4",
 },
 interferenceM1: {
 title: "Interference - Tactic in 1",
 explanationKey: "tacticInterference",
 manifestPath: "/data/pattern-tactics/interference/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference/m1",
 progressKey: "tactic-interference-m1",
 trainerKey: "tactic-interference-m1",
 },
 interferenceM2: {
 title: "Interference - Tactic in 2",
 explanationKey: "tacticInterference",
 manifestPath: "/data/pattern-tactics/interference/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference/m2",
 progressKey: "tactic-interference-m2",
 trainerKey: "tactic-interference-m2",
 },
 interferenceM3: {
 title: "Interference - Tactic in 3",
 explanationKey: "tacticInterference",
 manifestPath: "/data/pattern-tactics/interference/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference/m3",
 progressKey: "tactic-interference-m3",
 trainerKey: "tactic-interference-m3",
 },
 interferenceM4: {
 title: "Interference - Tactic in 4+",
 explanationKey: "tacticInterference",
 manifestPath: "/data/pattern-tactics/interference/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference/m4",
 progressKey: "tactic-interference-m4",
 trainerKey: "tactic-interference-m4",
 },
 interferenceSacrificeM1: {
 title: "Interference Sacrifice - Tactic in 1",
 explanationKey: "tacticInterferenceSacrifice",
 manifestPath: "/data/pattern-tactics/interference-sacrifice/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference-sacrifice/m1",
 progressKey: "tactic-interference-sacrifice-m1",
 trainerKey: "tactic-interference-sacrifice-m1",
 },
 interferenceSacrificeM2: {
 title: "Interference Sacrifice - Tactic in 2",
 explanationKey: "tacticInterferenceSacrifice",
 manifestPath: "/data/pattern-tactics/interference-sacrifice/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference-sacrifice/m2",
 progressKey: "tactic-interference-sacrifice-m2",
 trainerKey: "tactic-interference-sacrifice-m2",
 },
 interferenceSacrificeM3: {
 title: "Interference Sacrifice - Tactic in 3",
 explanationKey: "tacticInterferenceSacrifice",
 manifestPath: "/data/pattern-tactics/interference-sacrifice/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference-sacrifice/m3",
 progressKey: "tactic-interference-sacrifice-m3",
 trainerKey: "tactic-interference-sacrifice-m3",
 },
 interferenceSacrificeM4: {
 title: "Interference Sacrifice - Tactic in 4+",
 explanationKey: "tacticInterferenceSacrifice",
 manifestPath: "/data/pattern-tactics/interference-sacrifice/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/interference-sacrifice/m4",
 progressKey: "tactic-interference-sacrifice-m4",
 trainerKey: "tactic-interference-sacrifice-m4",
 },
 xrayQueenM1: {
 title: "Queen X-Ray Attack - Tactic in 1",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/queen-xray/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-xray/m1",
 progressKey: "tactic-xray-queen-m1",
 trainerKey: "tactic-xray-queen-m1",
 },
 xrayQueenM2: {
 title: "Queen X-Ray Attack - Tactic in 2",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/queen-xray/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-xray/m2",
 progressKey: "tactic-xray-queen-m2",
 trainerKey: "tactic-xray-queen-m2",
 },
 xrayQueenM3: {
 title: "Queen X-Ray Attack - Tactic in 3",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/queen-xray/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-xray/m3",
 progressKey: "tactic-xray-queen-m3",
 trainerKey: "tactic-xray-queen-m3",
 },
 xrayQueenM4: {
 title: "Queen X-Ray Attack - Tactic in 4+",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/queen-xray/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/queen-xray/m4",
 progressKey: "tactic-xray-queen-m4",
 trainerKey: "tactic-xray-queen-m4",
 },
 xrayRookM1: {
 title: "Rook X-Ray Attack - Tactic in 1",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/rook-xray/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-xray/m1",
 progressKey: "tactic-xray-rook-m1",
 trainerKey: "tactic-xray-rook-m1",
 },
 xrayRookM2: {
 title: "Rook X-Ray Attack - Tactic in 2",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/rook-xray/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-xray/m2",
 progressKey: "tactic-xray-rook-m2",
 trainerKey: "tactic-xray-rook-m2",
 },
 xrayRookM3: {
 title: "Rook X-Ray Attack - Tactic in 3",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/rook-xray/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-xray/m3",
 progressKey: "tactic-xray-rook-m3",
 trainerKey: "tactic-xray-rook-m3",
 },
 xrayRookM4: {
 title: "Rook X-Ray Attack - Tactic in 4+",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/rook-xray/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/rook-xray/m4",
 progressKey: "tactic-xray-rook-m4",
 trainerKey: "tactic-xray-rook-m4",
 },
 xrayBishopM1: {
 title: "Bishop X-Ray Attack - Tactic in 1",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/bishop-xray/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-xray/m1",
 progressKey: "tactic-xray-bishop-m1",
 trainerKey: "tactic-xray-bishop-m1",
 },
 xrayBishopM2: {
 title: "Bishop X-Ray Attack - Tactic in 2",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/bishop-xray/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-xray/m2",
 progressKey: "tactic-xray-bishop-m2",
 trainerKey: "tactic-xray-bishop-m2",
 },
 xrayBishopM3: {
 title: "Bishop X-Ray Attack - Tactic in 3",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/bishop-xray/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-xray/m3",
 progressKey: "tactic-xray-bishop-m3",
 trainerKey: "tactic-xray-bishop-m3",
 },
 xrayBishopM4: {
 title: "Bishop X-Ray Attack - Tactic in 4+",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/bishop-xray/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/bishop-xray/m4",
 progressKey: "tactic-xray-bishop-m4",
 trainerKey: "tactic-xray-bishop-m4",
 },
 xrayOtherM1: {
 title: "Other X-Ray Attack - Tactic in 1",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/other-xray/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-xray/m1",
 progressKey: "tactic-xray-other-m1",
 trainerKey: "tactic-xray-other-m1",
 },
 xrayOtherM2: {
 title: "Other X-Ray Attack - Tactic in 2",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/other-xray/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-xray/m2",
 progressKey: "tactic-xray-other-m2",
 trainerKey: "tactic-xray-other-m2",
 },
 xrayOtherM3: {
 title: "Other X-Ray Attack - Tactic in 3",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/other-xray/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-xray/m3",
 progressKey: "tactic-xray-other-m3",
 trainerKey: "tactic-xray-other-m3",
 },
 xrayOtherM4: {
 title: "Other X-Ray Attack - Tactic in 4+",
 explanationKey: "tacticXRayAttack",
 manifestPath: "/data/pattern-tactics/other-xray/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/other-xray/m4",
 progressKey: "tactic-xray-other-m4",
 trainerKey: "tactic-xray-other-m4",
 },
 promotionM1: {
 title: "Promotion - Tactic in 1",
 explanationKey: "tacticPromotion",
 manifestPath: "/data/pattern-tactics/promotion/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/promotion/m1",
 progressKey: "tactic-promotion-m1",
 trainerKey: "tactic-promotion-m1",
 },
 promotionM2: {
 title: "Promotion - Tactic in 2",
 explanationKey: "tacticPromotion",
 manifestPath: "/data/pattern-tactics/promotion/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/promotion/m2",
 progressKey: "tactic-promotion-m2",
 trainerKey: "tactic-promotion-m2",
 },
 promotionM3: {
 title: "Promotion - Tactic in 3",
 explanationKey: "tacticPromotion",
 manifestPath: "/data/pattern-tactics/promotion/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/promotion/m3",
 progressKey: "tactic-promotion-m3",
 trainerKey: "tactic-promotion-m3",
 },
 promotionM4: {
 title: "Promotion - Tactic in 4+",
 explanationKey: "tacticPromotion",
 manifestPath: "/data/pattern-tactics/promotion/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/promotion/m4",
 progressKey: "tactic-promotion-m4",
 trainerKey: "tactic-promotion-m4",
 },
 underpromotionM1: {
 title: "Underpromotion - Tactic in 1",
 explanationKey: "tacticUnderpromotion",
 manifestPath: "/data/pattern-tactics/underpromotion/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/underpromotion/m1",
 progressKey: "tactic-underpromotion-m1",
 trainerKey: "tactic-underpromotion-m1",
 },
 underpromotionM2: {
 title: "Underpromotion - Tactic in 2",
 explanationKey: "tacticUnderpromotion",
 manifestPath: "/data/pattern-tactics/underpromotion/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/underpromotion/m2",
 progressKey: "tactic-underpromotion-m2",
 trainerKey: "tactic-underpromotion-m2",
 },
 underpromotionM3: {
 title: "Underpromotion - Tactic in 3",
 explanationKey: "tacticUnderpromotion",
 manifestPath: "/data/pattern-tactics/underpromotion/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/underpromotion/m3",
 progressKey: "tactic-underpromotion-m3",
 trainerKey: "tactic-underpromotion-m3",
 },
 underpromotionM4: {
 title: "Underpromotion - Tactic in 4+",
 explanationKey: "tacticUnderpromotion",
 manifestPath: "/data/pattern-tactics/underpromotion/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/underpromotion/m4",
 progressKey: "tactic-underpromotion-m4",
 trainerKey: "tactic-underpromotion-m4",
 },
 underpromotionKnightM1: {
 title: "Knight Underpromotion - Tactic in 1",
 explanationKey: "tacticKnightUnderpromotion",
 manifestPath: "/data/pattern-tactics/knight-underpromotion/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-underpromotion/m1",
 progressKey: "tactic-underpromotion-knight-m1",
 trainerKey: "tactic-underpromotion-knight-m1",
 },
 underpromotionKnightM2: {
 title: "Knight Underpromotion - Tactic in 2",
 explanationKey: "tacticKnightUnderpromotion",
 manifestPath: "/data/pattern-tactics/knight-underpromotion/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-underpromotion/m2",
 progressKey: "tactic-underpromotion-knight-m2",
 trainerKey: "tactic-underpromotion-knight-m2",
 },
 underpromotionKnightM3: {
 title: "Knight Underpromotion - Tactic in 3",
 explanationKey: "tacticKnightUnderpromotion",
 manifestPath: "/data/pattern-tactics/knight-underpromotion/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-underpromotion/m3",
 progressKey: "tactic-underpromotion-knight-m3",
 trainerKey: "tactic-underpromotion-knight-m3",
 },
 underpromotionKnightM4: {
 title: "Knight Underpromotion - Tactic in 4+",
 explanationKey: "tacticKnightUnderpromotion",
 manifestPath: "/data/pattern-tactics/knight-underpromotion/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/knight-underpromotion/m4",
 progressKey: "tactic-underpromotion-knight-m4",
 trainerKey: "tactic-underpromotion-knight-m4",
 },
 enPassantM1: {
 title: "En Passant - Tactic in 1",
 explanationKey: "tacticEnPassant",
 manifestPath: "/data/pattern-tactics/en-passant/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/en-passant/m1",
 progressKey: "tactic-en-passant-m1",
 trainerKey: "tactic-en-passant-m1",
 },
 enPassantM2: {
 title: "En Passant - Tactic in 2",
 explanationKey: "tacticEnPassant",
 manifestPath: "/data/pattern-tactics/en-passant/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/en-passant/m2",
 progressKey: "tactic-en-passant-m2",
 trainerKey: "tactic-en-passant-m2",
 },
 enPassantM3: {
 title: "En Passant - Tactic in 3",
 explanationKey: "tacticEnPassant",
 manifestPath: "/data/pattern-tactics/en-passant/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/en-passant/m3",
 progressKey: "tactic-en-passant-m3",
 trainerKey: "tactic-en-passant-m3",
 },
 enPassantM4: {
 title: "En Passant - Tactic in 4+",
 explanationKey: "tacticEnPassant",
 manifestPath: "/data/pattern-tactics/en-passant/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/en-passant/m4",
 progressKey: "tactic-en-passant-m4",
 trainerKey: "tactic-en-passant-m4",
 },
 zugzwangM1: {
 title: "Zugzwang - Tactic in 1",
 explanationKey: "tacticZugzwang",
 manifestPath: "/data/pattern-tactics/zugzwang/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/zugzwang/m1",
 progressKey: "tactic-zugzwang-m1",
 trainerKey: "tactic-zugzwang-m1",
 },
 zugzwangM2: {
 title: "Zugzwang - Tactic in 2",
 explanationKey: "tacticZugzwang",
 manifestPath: "/data/pattern-tactics/zugzwang/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/zugzwang/m2",
 progressKey: "tactic-zugzwang-m2",
 trainerKey: "tactic-zugzwang-m2",
 },
 zugzwangM3: {
 title: "Zugzwang - Tactic in 3",
 explanationKey: "tacticZugzwang",
 manifestPath: "/data/pattern-tactics/zugzwang/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/zugzwang/m3",
 progressKey: "tactic-zugzwang-m3",
 trainerKey: "tactic-zugzwang-m3",
 },
 zugzwangM4: {
 title: "Zugzwang - Tactic in 4+",
 explanationKey: "tacticZugzwang",
 manifestPath: "/data/pattern-tactics/zugzwang/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/zugzwang/m4",
 progressKey: "tactic-zugzwang-m4",
 trainerKey: "tactic-zugzwang-m4",
 },
 zwischenzugM1: {
 title: "Zwischenzug / Intermezzo - Tactic in 1",
 explanationKey: "tacticZwischenzug",
 manifestPath: "/data/pattern-tactics/zwischenzug/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/zwischenzug/m1",
 progressKey: "tactic-zwischenzug-m1",
 trainerKey: "tactic-zwischenzug-m1",
 },
 zwischenzugM2: {
 title: "Zwischenzug / Intermezzo - Tactic in 2",
 explanationKey: "tacticZwischenzug",
 manifestPath: "/data/pattern-tactics/zwischenzug/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/zwischenzug/m2",
 progressKey: "tactic-zwischenzug-m2",
 trainerKey: "tactic-zwischenzug-m2",
 },
 zwischenzugM3: {
 title: "Zwischenzug / Intermezzo - Tactic in 3",
 explanationKey: "tacticZwischenzug",
 manifestPath: "/data/pattern-tactics/zwischenzug/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/zwischenzug/m3",
 progressKey: "tactic-zwischenzug-m3",
 trainerKey: "tactic-zwischenzug-m3",
 },
 zwischenzugM4: {
 title: "Zwischenzug / Intermezzo - Tactic in 4+",
 explanationKey: "tacticZwischenzug",
 manifestPath: "/data/pattern-tactics/zwischenzug/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/zwischenzug/m4",
 progressKey: "tactic-zwischenzug-m4",
 trainerKey: "tactic-zwischenzug-m4",
 },
 mixedM1: {
 title: "Mixed - Tactic in 1",
 explanationKey: "tacticMixed",
 manifestPath: "/data/pattern-tactics/mixed/m1/manifest.json",
 dataBasePath: "/data/pattern-tactics/mixed/m1",
 progressKey: "tactic-mixed-m1",
 trainerKey: "tactic-mixed-m1",
 },
 mixedM2: {
 title: "Mixed - Tactic in 2",
 explanationKey: "tacticMixed",
 manifestPath: "/data/pattern-tactics/mixed/m2/manifest.json",
 dataBasePath: "/data/pattern-tactics/mixed/m2",
 progressKey: "tactic-mixed-m2",
 trainerKey: "tactic-mixed-m2",
 },
 mixedM3: {
 title: "Mixed - Tactic in 3",
 explanationKey: "tacticMixed",
 manifestPath: "/data/pattern-tactics/mixed/m3/manifest.json",
 dataBasePath: "/data/pattern-tactics/mixed/m3",
 progressKey: "tactic-mixed-m3",
 trainerKey: "tactic-mixed-m3",
 },
 mixedM4: {
 title: "Mixed - Tactic in 4+",
 explanationKey: "tacticMixed",
 manifestPath: "/data/pattern-tactics/mixed/m4/manifest.json",
 dataBasePath: "/data/pattern-tactics/mixed/m4",
 progressKey: "tactic-mixed-m4",
 trainerKey: "tactic-mixed-m4",
 },
}

export const patternTacticConfigByRoute = {
 "m1/defense": patternTacticPageConfigs.defenseM1,
 "m2/defense": patternTacticPageConfigs.defenseM2,
 "m3/defense": patternTacticPageConfigs.defenseM3,
 "m4/defense": patternTacticPageConfigs.defenseM4,
 "m1/advanced-pawn": patternTacticPageConfigs.advancedPawnM1,
 "m2/advanced-pawn": patternTacticPageConfigs.advancedPawnM2,
 "m3/advanced-pawn": patternTacticPageConfigs.advancedPawnM3,
 "m4/advanced-pawn": patternTacticPageConfigs.advancedPawnM4,
 "m1/quiet-move": patternTacticPageConfigs.quietMoveM1,
 "m2/quiet-move": patternTacticPageConfigs.quietMoveM2,
 "m3/quiet-move": patternTacticPageConfigs.quietMoveM3,
 "m4/quiet-move": patternTacticPageConfigs.quietMoveM4,
 "m1/discovered-attack": patternTacticPageConfigs.discoveredAttackM1,
 "m2/discovered-attack": patternTacticPageConfigs.discoveredAttackM2,
 "m3/discovered-attack": patternTacticPageConfigs.discoveredAttackM3,
 "m4/discovered-attack": patternTacticPageConfigs.discoveredAttackM4,
 "m1/discovered-check": patternTacticPageConfigs.discoveredCheckM1,
 "m2/discovered-check": patternTacticPageConfigs.discoveredCheckM2,
 "m3/discovered-check": patternTacticPageConfigs.discoveredCheckM3,
 "m4/discovered-check": patternTacticPageConfigs.discoveredCheckM4,
 "m1/double-check": patternTacticPageConfigs.doubleCheckM1,
 "m2/double-check": patternTacticPageConfigs.doubleCheckM2,
 "m3/double-check": patternTacticPageConfigs.doubleCheckM3,
 "m4/double-check": patternTacticPageConfigs.doubleCheckM4,
 "m1/knight-fork": patternTacticPageConfigs.forkKnightM1,
 "m2/knight-fork": patternTacticPageConfigs.forkKnightM2,
 "m3/knight-fork": patternTacticPageConfigs.forkKnightM3,
 "m4/knight-fork": patternTacticPageConfigs.forkKnightM4,
 "m1/queen-fork": patternTacticPageConfigs.forkQueenM1,
 "m2/queen-fork": patternTacticPageConfigs.forkQueenM2,
 "m3/queen-fork": patternTacticPageConfigs.forkQueenM3,
 "m4/queen-fork": patternTacticPageConfigs.forkQueenM4,
 "m1/rook-fork": patternTacticPageConfigs.forkRookM1,
 "m2/rook-fork": patternTacticPageConfigs.forkRookM2,
 "m3/rook-fork": patternTacticPageConfigs.forkRookM3,
 "m4/rook-fork": patternTacticPageConfigs.forkRookM4,
 "m1/bishop-fork": patternTacticPageConfigs.forkBishopM1,
 "m2/bishop-fork": patternTacticPageConfigs.forkBishopM2,
 "m3/bishop-fork": patternTacticPageConfigs.forkBishopM3,
 "m4/bishop-fork": patternTacticPageConfigs.forkBishopM4,
 "m1/pawn-fork": patternTacticPageConfigs.forkPawnM1,
 "m2/pawn-fork": patternTacticPageConfigs.forkPawnM2,
 "m3/pawn-fork": patternTacticPageConfigs.forkPawnM3,
 "m4/pawn-fork": patternTacticPageConfigs.forkPawnM4,
 "m1/king-fork": patternTacticPageConfigs.forkKingM1,
 "m3/king-fork": patternTacticPageConfigs.forkKingM3,
 "m4/king-fork": patternTacticPageConfigs.forkKingM4,
 "m1/rook-pin": patternTacticPageConfigs.pinRookM1,
 "m2/rook-pin": patternTacticPageConfigs.pinRookM2,
 "m3/rook-pin": patternTacticPageConfigs.pinRookM3,
 "m4/rook-pin": patternTacticPageConfigs.pinRookM4,
 "m1/queen-pin": patternTacticPageConfigs.pinQueenM1,
 "m2/queen-pin": patternTacticPageConfigs.pinQueenM2,
 "m3/queen-pin": patternTacticPageConfigs.pinQueenM3,
 "m4/queen-pin": patternTacticPageConfigs.pinQueenM4,
 "m1/bishop-pin": patternTacticPageConfigs.pinBishopM1,
 "m2/bishop-pin": patternTacticPageConfigs.pinBishopM2,
 "m3/bishop-pin": patternTacticPageConfigs.pinBishopM3,
 "m4/bishop-pin": patternTacticPageConfigs.pinBishopM4,
 "m1/other-pin": patternTacticPageConfigs.pinOtherM1,
 "m2/other-pin": patternTacticPageConfigs.pinOtherM2,
 "m3/other-pin": patternTacticPageConfigs.pinOtherM3,
 "m4/other-pin": patternTacticPageConfigs.pinOtherM4,
 "m1/rook-skewer": patternTacticPageConfigs.skewerRookM1,
 "m2/rook-skewer": patternTacticPageConfigs.skewerRookM2,
 "m3/rook-skewer": patternTacticPageConfigs.skewerRookM3,
 "m4/rook-skewer": patternTacticPageConfigs.skewerRookM4,
 "m1/queen-skewer": patternTacticPageConfigs.skewerQueenM1,
 "m2/queen-skewer": patternTacticPageConfigs.skewerQueenM2,
 "m3/queen-skewer": patternTacticPageConfigs.skewerQueenM3,
 "m4/queen-skewer": patternTacticPageConfigs.skewerQueenM4,
 "m1/bishop-skewer": patternTacticPageConfigs.skewerBishopM1,
 "m2/bishop-skewer": patternTacticPageConfigs.skewerBishopM2,
 "m3/bishop-skewer": patternTacticPageConfigs.skewerBishopM3,
 "m4/bishop-skewer": patternTacticPageConfigs.skewerBishopM4,
 "m1/other-skewer": patternTacticPageConfigs.skewerOtherM1,
 "m2/other-skewer": patternTacticPageConfigs.skewerOtherM2,
 "m3/other-skewer": patternTacticPageConfigs.skewerOtherM3,
 "m4/other-skewer": patternTacticPageConfigs.skewerOtherM4,
 "m1/decoy-attraction": patternTacticPageConfigs.decoyAttractionM1,
 "m2/decoy-attraction": patternTacticPageConfigs.decoyAttractionM2,
 "m3/decoy-attraction": patternTacticPageConfigs.decoyAttractionM3,
 "m4/decoy-attraction": patternTacticPageConfigs.decoyAttractionM4,
 "m1/deflection": patternTacticPageConfigs.deflectionM1,
 "m2/deflection": patternTacticPageConfigs.deflectionM2,
 "m3/deflection": patternTacticPageConfigs.deflectionM3,
 "m4/deflection": patternTacticPageConfigs.deflectionM4,
 "m1/decoy-deflection": patternTacticPageConfigs.decoyDeflectionCombinedM1,
 "m2/decoy-deflection": patternTacticPageConfigs.decoyDeflectionCombinedM2,
 "m3/decoy-deflection": patternTacticPageConfigs.decoyDeflectionCombinedM3,
 "m4/decoy-deflection": patternTacticPageConfigs.decoyDeflectionCombinedM4,
 "m1/hanging-piece": patternTacticPageConfigs.hangingPieceM1,
 "m2/hanging-piece": patternTacticPageConfigs.hangingPieceM2,
 "m3/hanging-piece": patternTacticPageConfigs.hangingPieceM3,
 "m4/hanging-piece": patternTacticPageConfigs.hangingPieceM4,
 "m1/trapped-piece": patternTacticPageConfigs.trappedPieceM1,
 "m2/trapped-piece": patternTacticPageConfigs.trappedPieceM2,
 "m3/trapped-piece": patternTacticPageConfigs.trappedPieceM3,
 "m4/trapped-piece": patternTacticPageConfigs.trappedPieceM4,
 "m1/remove-the-defender": patternTacticPageConfigs.removeTheDefenderM1,
 "m2/remove-the-defender": patternTacticPageConfigs.removeTheDefenderM2,
 "m3/remove-the-defender": patternTacticPageConfigs.removeTheDefenderM3,
 "m4/remove-the-defender": patternTacticPageConfigs.removeTheDefenderM4,
 "m1/vulnerable-king": patternTacticPageConfigs.vulnerableKingM1,
 "m3/vulnerable-king": patternTacticPageConfigs.vulnerableKingM3,
 "m4/vulnerable-king": patternTacticPageConfigs.vulnerableKingM4,
 "m1/kingside-attack": patternTacticPageConfigs.kingsideAttackM1,
 "m2/kingside-attack": patternTacticPageConfigs.kingsideAttackM2,
 "m3/kingside-attack": patternTacticPageConfigs.kingsideAttackM3,
 "m4/kingside-attack": patternTacticPageConfigs.kingsideAttackM4,
 "m1/queenside-attack": patternTacticPageConfigs.queensideAttackM1,
 "m2/queenside-attack": patternTacticPageConfigs.queensideAttackM2,
 "m3/queenside-attack": patternTacticPageConfigs.queensideAttackM3,
 "m4/queenside-attack": patternTacticPageConfigs.queensideAttackM4,
 "m1/attacking-f2-f7": patternTacticPageConfigs.attackingF2F7M1,
 "m2/attacking-f2-f7": patternTacticPageConfigs.attackingF2F7M2,
 "m3/attacking-f2-f7": patternTacticPageConfigs.attackingF2F7M3,
 "m4/attacking-f2-f7": patternTacticPageConfigs.attackingF2F7M4,
 "m1/queen-sacrifice": patternTacticPageConfigs.sacrificeQueenM1,
 "m2/queen-sacrifice": patternTacticPageConfigs.sacrificeQueenM2,
 "m3/queen-sacrifice": patternTacticPageConfigs.sacrificeQueenM3,
 "m4/queen-sacrifice": patternTacticPageConfigs.sacrificeQueenM4,
 "m1/rook-sacrifice": patternTacticPageConfigs.sacrificeRookM1,
 "m2/rook-sacrifice": patternTacticPageConfigs.sacrificeRookM2,
 "m3/rook-sacrifice": patternTacticPageConfigs.sacrificeRookM3,
 "m4/rook-sacrifice": patternTacticPageConfigs.sacrificeRookM4,
 "m1/bishop-sacrifice": patternTacticPageConfigs.sacrificeBishopM1,
 "m2/bishop-sacrifice": patternTacticPageConfigs.sacrificeBishopM2,
 "m3/bishop-sacrifice": patternTacticPageConfigs.sacrificeBishopM3,
 "m4/bishop-sacrifice": patternTacticPageConfigs.sacrificeBishopM4,
 "m1/knight-sacrifice": patternTacticPageConfigs.sacrificeKnightM1,
 "m2/knight-sacrifice": patternTacticPageConfigs.sacrificeKnightM2,
 "m3/knight-sacrifice": patternTacticPageConfigs.sacrificeKnightM3,
 "m4/knight-sacrifice": patternTacticPageConfigs.sacrificeKnightM4,
 "m1/pawn-sacrifice": patternTacticPageConfigs.sacrificePawnM1,
 "m2/pawn-sacrifice": patternTacticPageConfigs.sacrificePawnM2,
 "m3/pawn-sacrifice": patternTacticPageConfigs.sacrificePawnM3,
 "m4/pawn-sacrifice": patternTacticPageConfigs.sacrificePawnM4,
 "m1/king-sacrifice": patternTacticPageConfigs.sacrificeKingM1,
 "m2/king-sacrifice": patternTacticPageConfigs.sacrificeKingM2,
 "m3/king-sacrifice": patternTacticPageConfigs.sacrificeKingM3,
 "m4/king-sacrifice": patternTacticPageConfigs.sacrificeKingM4,
 "m1/clearance": patternTacticPageConfigs.clearanceM1,
 "m2/clearance": patternTacticPageConfigs.clearanceM2,
 "m3/clearance": patternTacticPageConfigs.clearanceM3,
 "m4/clearance": patternTacticPageConfigs.clearanceM4,
 "m1/clearance-sacrifice": patternTacticPageConfigs.clearanceSacrificeM1,
 "m2/clearance-sacrifice": patternTacticPageConfigs.clearanceSacrificeM2,
 "m3/clearance-sacrifice": patternTacticPageConfigs.clearanceSacrificeM3,
 "m4/clearance-sacrifice": patternTacticPageConfigs.clearanceSacrificeM4,
 "m1/interference": patternTacticPageConfigs.interferenceM1,
 "m2/interference": patternTacticPageConfigs.interferenceM2,
 "m3/interference": patternTacticPageConfigs.interferenceM3,
 "m4/interference": patternTacticPageConfigs.interferenceM4,
 "m1/interference-sacrifice": patternTacticPageConfigs.interferenceSacrificeM1,
 "m2/interference-sacrifice": patternTacticPageConfigs.interferenceSacrificeM2,
 "m3/interference-sacrifice": patternTacticPageConfigs.interferenceSacrificeM3,
 "m4/interference-sacrifice": patternTacticPageConfigs.interferenceSacrificeM4,
 "m1/queen-xray": patternTacticPageConfigs.xrayQueenM1,
 "m2/queen-xray": patternTacticPageConfigs.xrayQueenM2,
 "m3/queen-xray": patternTacticPageConfigs.xrayQueenM3,
 "m4/queen-xray": patternTacticPageConfigs.xrayQueenM4,
 "m1/rook-xray": patternTacticPageConfigs.xrayRookM1,
 "m2/rook-xray": patternTacticPageConfigs.xrayRookM2,
 "m3/rook-xray": patternTacticPageConfigs.xrayRookM3,
 "m4/rook-xray": patternTacticPageConfigs.xrayRookM4,
 "m1/bishop-xray": patternTacticPageConfigs.xrayBishopM1,
 "m2/bishop-xray": patternTacticPageConfigs.xrayBishopM2,
 "m3/bishop-xray": patternTacticPageConfigs.xrayBishopM3,
 "m4/bishop-xray": patternTacticPageConfigs.xrayBishopM4,
 "m1/other-xray": patternTacticPageConfigs.xrayOtherM1,
 "m2/other-xray": patternTacticPageConfigs.xrayOtherM2,
 "m3/other-xray": patternTacticPageConfigs.xrayOtherM3,
 "m4/other-xray": patternTacticPageConfigs.xrayOtherM4,
 "m1/promotion": patternTacticPageConfigs.promotionM1,
 "m2/promotion": patternTacticPageConfigs.promotionM2,
 "m3/promotion": patternTacticPageConfigs.promotionM3,
 "m4/promotion": patternTacticPageConfigs.promotionM4,
 "m1/underpromotion": patternTacticPageConfigs.underpromotionM1,
 "m2/underpromotion": patternTacticPageConfigs.underpromotionM2,
 "m3/underpromotion": patternTacticPageConfigs.underpromotionM3,
 "m4/underpromotion": patternTacticPageConfigs.underpromotionM4,
 "m1/knight-underpromotion": patternTacticPageConfigs.underpromotionKnightM1,
 "m2/knight-underpromotion": patternTacticPageConfigs.underpromotionKnightM2,
 "m3/knight-underpromotion": patternTacticPageConfigs.underpromotionKnightM3,
 "m4/knight-underpromotion": patternTacticPageConfigs.underpromotionKnightM4,
 "m1/en-passant": patternTacticPageConfigs.enPassantM1,
 "m2/en-passant": patternTacticPageConfigs.enPassantM2,
 "m3/en-passant": patternTacticPageConfigs.enPassantM3,
 "m4/en-passant": patternTacticPageConfigs.enPassantM4,
 "m1/zugzwang": patternTacticPageConfigs.zugzwangM1,
 "m2/zugzwang": patternTacticPageConfigs.zugzwangM2,
 "m3/zugzwang": patternTacticPageConfigs.zugzwangM3,
 "m4/zugzwang": patternTacticPageConfigs.zugzwangM4,
 "m1/zwischenzug": patternTacticPageConfigs.zwischenzugM1,
 "m2/zwischenzug": patternTacticPageConfigs.zwischenzugM2,
 "m3/zwischenzug": patternTacticPageConfigs.zwischenzugM3,
 "m4/zwischenzug": patternTacticPageConfigs.zwischenzugM4,
 "m1/mixed": patternTacticPageConfigs.mixedM1,
 "m2/mixed": patternTacticPageConfigs.mixedM2,
 "m3/mixed": patternTacticPageConfigs.mixedM3,
 "m4/mixed": patternTacticPageConfigs.mixedM4,
}

export type PatternTacticPageConfigKey = keyof typeof patternTacticPageConfigs
