import { patternTacticConfigByRoute } from "../trainers/patternTactic/pageConfigs"

export type StudyType = "chunk" | "line" | "game" | "vision"
export type TrainerCategory =
 | "mates"
  | "tactics"
 | "endgames"
 | "board-vision"
 | "master-games"
 | "openings"

export type TrainerCatalogEntry = {
 trainerKey: string
 route: string
 title: string
 category: TrainerCategory
 studyType: StudyType
 autoEnabled: boolean
 sortOrder: number
}

export const TRAINER_CATALOG: TrainerCatalogEntry[] = [
 // =====================
 // MATES - ALL ACTIVE PATTERN TRAINERS
 // =====================
 {
 trainerKey: "anastasia-mate-1",
 route: "/mates/m1/anastasia",
 title: "Anastasia Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 10,
 },
 {
 trainerKey: "anastasia-mate-2",
 route: "/mates/m2/anastasia",
 title: "Anastasia Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 20,
 },
 {
 trainerKey: "anastasia-mate-in-3",
 route: "/mates/m3/anastasia",
 title: "Anastasia Mate in 3",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 30,
 },
 {
 trainerKey: "anastasia-mate-in-4",
 route: "/mates/m4/anastasia",
 title: "Anastasia Mate in 4",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 40,
 },
 {
 trainerKey: "anastasia-mate-in-5",
 route: "/mates/m5/anastasia",
 title: "Anastasia Mate in 5",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 50,
 },
 {
 trainerKey: "back-rank-mate-1",
 route: "/mates/m1/back-rank",
 title: "Back Rank Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 60,
 },
 {
 trainerKey: "back-rank-mate-2",
 route: "/mates/m2/back-rank",
 title: "Back Rank Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 70,
 },
 {
 trainerKey: "back-rank-mate-3",
 route: "/mates/m3/back-rank",
 title: "Back Rank Mate in 3",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 80,
 },
 {
 trainerKey: "back-rank-mate-4",
 route: "/mates/m4/back-rank",
 title: "Back Rank Mate in 4",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 90,
 },
 {
 trainerKey: "back-rank-mate-5",
 route: "/mates/m5/back-rank",
 title: "Back Rank Mate in 5",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 100,
 },
 {
 trainerKey: "arabian-mate-1",
 route: "/mates/m1/arabian",
 title: "Arabian Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 110,
 },
 {
 trainerKey: "arabian-mate-2",
 route: "/mates/m2/arabian",
 title: "Arabian Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 120,
 },
 {
 trainerKey: "arabian-mate-3",
 route: "/mates/m3/arabian",
 title: "Arabian Mate in 3",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 130,
 },
 {
 trainerKey: "arabian-mate-4",
 route: "/mates/m4/arabian",
 title: "Arabian Mate in 4",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 140,
 },
 {
 trainerKey: "arabian-mate-5",
 route: "/mates/m5/arabian",
 title: "Arabian Mate in 5",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 150,
 },
 {
 trainerKey: "boden-mate-1",
 route: "/mates/m1/boden",
 title: "Boden Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 160,
 },
 {
 trainerKey: "boden-mate-2",
 route: "/mates/m2/boden",
 title: "Boden Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 170,
 },
 {
 trainerKey: "boden-mate-3",
 route: "/mates/m3/boden",
 title: "Boden Mate in 3+",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 180,
 },
 {
 trainerKey: "smothered-mate-1",
 route: "/mates/m1/smothered",
 title: "Smothered Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 190,
 },
 {
 trainerKey: "smothered-mate-2",
 route: "/mates/m2/smothered",
 title: "Smothered Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 200,
 },
 {
 trainerKey: "smothered-mate-3",
 route: "/mates/m3/smothered",
 title: "Smothered Mate in 3",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 210,
 },
 {
 trainerKey: "smothered-mate-4",
 route: "/mates/m4/smothered",
 title: "Smothered Mate in 4",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 220,
 },
 {
 trainerKey: "hook-mate-1",
 route: "/mates/m1/hook",
 title: "Hook Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 230,
 },
 {
 trainerKey: "hook-mate-2",
 route: "/mates/m2/hook",
 title: "Hook Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 240,
 },
 {
 trainerKey: "hook-mate-3",
 route: "/mates/m3/hook",
 title: "Hook Mate in 3",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 250,
 },
 {
 trainerKey: "hook-mate-4",
 route: "/mates/m4/hook",
 title: "Hook Mate in 4",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 260,
 },
 {
 trainerKey: "hook-mate-5",
 route: "/mates/m5/hook",
 title: "Hook Mate in 5",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 270,
 },
 {
 trainerKey: "kill-box-mate-1",
 route: "/mates/m1/kill-box",
 title: "Kill Box Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 280,
 },
 {
 trainerKey: "kill-box-mate-2",
 route: "/mates/m2/kill-box",
 title: "Kill Box Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 290,
 },
 {
 trainerKey: "kill-box-mate-3",
 route: "/mates/m3/kill-box",
 title: "Kill Box Mate in 3",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 300,
 },
 {
 trainerKey: "kill-box-mate-4",
 route: "/mates/m4/kill-box",
 title: "Kill Box Mate in 4",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 310,
 },
 {
 trainerKey: "kill-box-mate-5",
 route: "/mates/m5/kill-box",
 title: "Kill Box Mate in 5",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 320,
 },
 {
 trainerKey: "dovetail-mate-1",
 route: "/mates/m1/dovetail",
 title: "Dovetail Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 330,
 },
 {
 trainerKey: "dovetail-mate-2",
 route: "/mates/m2/dovetail",
 title: "Dovetail Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 340,
 },
 {
 trainerKey: "dovetail-mate-3",
 route: "/mates/m3/dovetail",
 title: "Dovetail Mate in 3",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 350,
 },
 {
 trainerKey: "dovetail-mate-4",
 route: "/mates/m4/dovetail",
 title: "Dovetail Mate in 4",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 360,
 },
 {
 trainerKey: "dovetail-mate-5",
 route: "/mates/m5/dovetail",
 title: "Dovetail Mate in 5",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 370,
 },
 {
 trainerKey: "double-bishop-mate-1",
 route: "/mates/m1/double-bishop",
 title: "Double Bishop Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 380,
 },
 {
 trainerKey: "double-bishop-mate-2",
 route: "/mates/m2/double-bishop",
 title: "Double Bishop Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 390,
 },
 {
 trainerKey: "double-bishop-mate-3-plus",
 route: "/mates/m3/double-bishop",
 title: "Double Bishop Mate in 3+",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 400,
 },
 {
 trainerKey: "mixed-mate-1",
 route: "/mates/m1/mixed",
 title: "Mixed Mate in 1",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 410,
 },
 {
 trainerKey: "mixed-mate-2",
 route: "/mates/m2/mixed",
 title: "Mixed Mate in 2",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 420,
 },
 {
 trainerKey: "mixed-mate-3",
 route: "/mates/m3/mixed",
 title: "Mixed Mate in 3",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 430,
 },
 {
 trainerKey: "mixed-mate-4",
 route: "/mates/m4/mixed",
 title: "Mixed Mate in 4",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 440,
 },
 {
 trainerKey: "mixed-mate-5",
 route: "/mates/m5/mixed",
 title: "Mixed Mate in 5",
 category: "mates",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 450,
 },

 // =====================
 // ENDGAMES (example)
 // =====================
 {
 trainerKey: "kqk-basic",
 route: "/endgame/piece-mates/kqk",
 title: "King + Queen vs King",
 category: "endgames",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 100,
 },
 {
 trainerKey: "krk-basic",
 route: "/endgame/piece-mates/krk",
 title: "King + Rook vs King",
 category: "endgames",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 110,
 },
  {
  trainerKey: "stalemate-underpromotion",
  route: "/stalemate/underpromotion",
  title: "Stalemate Underpromotion",
  category: "endgames",
  studyType: "chunk",
  autoEnabled: true,
  sortOrder: 120,
  },


 // =====================
// TACTICS - ALL ACTIVE PATTERN TRAINERS
// =====================
 {
 trainerKey: "tactic-defense-m1",
 route: "/tactics/m1/defense",
 title: "Defense - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5000,
 },
 {
 trainerKey: "tactic-defense-m2",
 route: "/tactics/m2/defense",
 title: "Defense - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5010,
 },
 {
 trainerKey: "tactic-defense-m3",
 route: "/tactics/m3/defense",
 title: "Defense - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5020,
 },
 {
 trainerKey: "tactic-defense-m4",
 route: "/tactics/m4/defense",
 title: "Defense - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5030,
 },
 {
 trainerKey: "tactic-advanced-pawn-m1",
 route: "/tactics/m1/advanced-pawn",
 title: "Advanced Pawn - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5040,
 },
 {
 trainerKey: "tactic-advanced-pawn-m2",
 route: "/tactics/m2/advanced-pawn",
 title: "Advanced Pawn - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5050,
 },
 {
 trainerKey: "tactic-advanced-pawn-m3",
 route: "/tactics/m3/advanced-pawn",
 title: "Advanced Pawn - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5060,
 },
 {
 trainerKey: "tactic-advanced-pawn-m4",
 route: "/tactics/m4/advanced-pawn",
 title: "Advanced Pawn - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5070,
 },
 {
 trainerKey: "tactic-quiet-move-m1",
 route: "/tactics/m1/quiet-move",
 title: "Quiet Move - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5080,
 },
 {
 trainerKey: "tactic-quiet-move-m2",
 route: "/tactics/m2/quiet-move",
 title: "Quiet Move - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5090,
 },
 {
 trainerKey: "tactic-quiet-move-m3",
 route: "/tactics/m3/quiet-move",
 title: "Quiet Move - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5100,
 },
 {
 trainerKey: "tactic-quiet-move-m4",
 route: "/tactics/m4/quiet-move",
 title: "Quiet Move - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5110,
 },
 {
 trainerKey: "tactic-discovered-attack-m1",
 route: "/tactics/m1/discovered-attack",
 title: "Discovered Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5120,
 },
 {
 trainerKey: "tactic-discovered-attack-m2",
 route: "/tactics/m2/discovered-attack",
 title: "Discovered Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5130,
 },
 {
 trainerKey: "tactic-discovered-attack-m3",
 route: "/tactics/m3/discovered-attack",
 title: "Discovered Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5140,
 },
 {
 trainerKey: "tactic-discovered-attack-m4",
 route: "/tactics/m4/discovered-attack",
 title: "Discovered Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5150,
 },
 {
 trainerKey: "tactic-discovered-check-m1",
 route: "/tactics/m1/discovered-check",
 title: "Discovered Check - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5160,
 },
 {
 trainerKey: "tactic-discovered-check-m2",
 route: "/tactics/m2/discovered-check",
 title: "Discovered Check - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5170,
 },
 {
 trainerKey: "tactic-discovered-check-m3",
 route: "/tactics/m3/discovered-check",
 title: "Discovered Check - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5180,
 },
 {
 trainerKey: "tactic-discovered-check-m4",
 route: "/tactics/m4/discovered-check",
 title: "Discovered Check - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5190,
 },
 {
 trainerKey: "tactic-double-check-m1",
 route: "/tactics/m1/double-check",
 title: "Double Check - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5200,
 },
 {
 trainerKey: "tactic-double-check-m2",
 route: "/tactics/m2/double-check",
 title: "Double Check - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5210,
 },
 {
 trainerKey: "tactic-double-check-m3",
 route: "/tactics/m3/double-check",
 title: "Double Check - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5220,
 },
 {
 trainerKey: "tactic-double-check-m4",
 route: "/tactics/m4/double-check",
 title: "Double Check - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5230,
 },
 {
 trainerKey: "tactic-fork-knight-m1",
 route: "/tactics/m1/knight-fork",
 title: "Knight Fork / Double Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5240,
 },
 {
 trainerKey: "tactic-fork-knight-m2",
 route: "/tactics/m2/knight-fork",
 title: "Knight Fork / Double Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5250,
 },
 {
 trainerKey: "tactic-fork-knight-m3",
 route: "/tactics/m3/knight-fork",
 title: "Knight Fork / Double Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5260,
 },
 {
 trainerKey: "tactic-fork-knight-m4",
 route: "/tactics/m4/knight-fork",
 title: "Knight Fork / Double Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5270,
 },
 {
 trainerKey: "tactic-fork-queen-m1",
 route: "/tactics/m1/queen-fork",
 title: "Queen Fork / Double Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5280,
 },
 {
 trainerKey: "tactic-fork-queen-m2",
 route: "/tactics/m2/queen-fork",
 title: "Queen Fork / Double Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5290,
 },
 {
 trainerKey: "tactic-fork-queen-m3",
 route: "/tactics/m3/queen-fork",
 title: "Queen Fork / Double Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5300,
 },
 {
 trainerKey: "tactic-fork-queen-m4",
 route: "/tactics/m4/queen-fork",
 title: "Queen Fork / Double Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5310,
 },
 {
 trainerKey: "tactic-fork-rook-m1",
 route: "/tactics/m1/rook-fork",
 title: "Rook Fork / Double Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5320,
 },
 {
 trainerKey: "tactic-fork-rook-m2",
 route: "/tactics/m2/rook-fork",
 title: "Rook Fork / Double Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5330,
 },
 {
 trainerKey: "tactic-fork-rook-m3",
 route: "/tactics/m3/rook-fork",
 title: "Rook Fork / Double Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5340,
 },
 {
 trainerKey: "tactic-fork-rook-m4",
 route: "/tactics/m4/rook-fork",
 title: "Rook Fork / Double Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5350,
 },
 {
 trainerKey: "tactic-fork-bishop-m1",
 route: "/tactics/m1/bishop-fork",
 title: "Bishop Fork / Double Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5360,
 },
 {
 trainerKey: "tactic-fork-bishop-m2",
 route: "/tactics/m2/bishop-fork",
 title: "Bishop Fork / Double Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5370,
 },
 {
 trainerKey: "tactic-fork-bishop-m3",
 route: "/tactics/m3/bishop-fork",
 title: "Bishop Fork / Double Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5380,
 },
 {
 trainerKey: "tactic-fork-bishop-m4",
 route: "/tactics/m4/bishop-fork",
 title: "Bishop Fork / Double Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5390,
 },
 {
 trainerKey: "tactic-fork-pawn-m1",
 route: "/tactics/m1/pawn-fork",
 title: "Pawn Fork / Double Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5400,
 },
 {
 trainerKey: "tactic-fork-pawn-m2",
 route: "/tactics/m2/pawn-fork",
 title: "Pawn Fork / Double Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5410,
 },
 {
 trainerKey: "tactic-fork-pawn-m3",
 route: "/tactics/m3/pawn-fork",
 title: "Pawn Fork / Double Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5420,
 },
 {
 trainerKey: "tactic-fork-pawn-m4",
 route: "/tactics/m4/pawn-fork",
 title: "Pawn Fork / Double Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5430,
 },
 {
 trainerKey: "tactic-fork-king-m1",
 route: "/tactics/m1/king-fork",
 title: "King Fork / Double Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5440,
 },
 {
 trainerKey: "tactic-fork-king-m3",
 route: "/tactics/m3/king-fork",
 title: "King Fork / Double Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5450,
 },
 {
 trainerKey: "tactic-fork-king-m4",
 route: "/tactics/m4/king-fork",
 title: "King Fork / Double Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5460,
 },
 {
 trainerKey: "tactic-pin-rook-m1",
 route: "/tactics/m1/rook-pin",
 title: "Rook Pin - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5470,
 },
 {
 trainerKey: "tactic-pin-rook-m2",
 route: "/tactics/m2/rook-pin",
 title: "Rook Pin - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5480,
 },
 {
 trainerKey: "tactic-pin-rook-m3",
 route: "/tactics/m3/rook-pin",
 title: "Rook Pin - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5490,
 },
 {
 trainerKey: "tactic-pin-rook-m4",
 route: "/tactics/m4/rook-pin",
 title: "Rook Pin - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5500,
 },
 {
 trainerKey: "tactic-pin-queen-m1",
 route: "/tactics/m1/queen-pin",
 title: "Queen Pin - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5510,
 },
 {
 trainerKey: "tactic-pin-queen-m2",
 route: "/tactics/m2/queen-pin",
 title: "Queen Pin - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5520,
 },
 {
 trainerKey: "tactic-pin-queen-m3",
 route: "/tactics/m3/queen-pin",
 title: "Queen Pin - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5530,
 },
 {
 trainerKey: "tactic-pin-queen-m4",
 route: "/tactics/m4/queen-pin",
 title: "Queen Pin - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5540,
 },
 {
 trainerKey: "tactic-pin-bishop-m1",
 route: "/tactics/m1/bishop-pin",
 title: "Bishop Pin - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5550,
 },
 {
 trainerKey: "tactic-pin-bishop-m2",
 route: "/tactics/m2/bishop-pin",
 title: "Bishop Pin - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5560,
 },
 {
 trainerKey: "tactic-pin-bishop-m3",
 route: "/tactics/m3/bishop-pin",
 title: "Bishop Pin - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5570,
 },
 {
 trainerKey: "tactic-pin-bishop-m4",
 route: "/tactics/m4/bishop-pin",
 title: "Bishop Pin - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5580,
 },
 {
 trainerKey: "tactic-pin-other-m1",
 route: "/tactics/m1/other-pin",
 title: "Other Pin - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5590,
 },
 {
 trainerKey: "tactic-pin-other-m2",
 route: "/tactics/m2/other-pin",
 title: "Other Pin - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5600,
 },
 {
 trainerKey: "tactic-pin-other-m3",
 route: "/tactics/m3/other-pin",
 title: "Other Pin - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5610,
 },
 {
 trainerKey: "tactic-pin-other-m4",
 route: "/tactics/m4/other-pin",
 title: "Other Pin - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5620,
 },
 {
 trainerKey: "tactic-skewer-rook-m1",
 route: "/tactics/m1/rook-skewer",
 title: "Rook Skewer - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5630,
 },
 {
 trainerKey: "tactic-skewer-rook-m2",
 route: "/tactics/m2/rook-skewer",
 title: "Rook Skewer - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5640,
 },
 {
 trainerKey: "tactic-skewer-rook-m3",
 route: "/tactics/m3/rook-skewer",
 title: "Rook Skewer - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5650,
 },
 {
 trainerKey: "tactic-skewer-rook-m4",
 route: "/tactics/m4/rook-skewer",
 title: "Rook Skewer - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5660,
 },
 {
 trainerKey: "tactic-skewer-queen-m1",
 route: "/tactics/m1/queen-skewer",
 title: "Queen Skewer - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5670,
 },
 {
 trainerKey: "tactic-skewer-queen-m2",
 route: "/tactics/m2/queen-skewer",
 title: "Queen Skewer - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5680,
 },
 {
 trainerKey: "tactic-skewer-queen-m3",
 route: "/tactics/m3/queen-skewer",
 title: "Queen Skewer - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5690,
 },
 {
 trainerKey: "tactic-skewer-queen-m4",
 route: "/tactics/m4/queen-skewer",
 title: "Queen Skewer - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5700,
 },
 {
 trainerKey: "tactic-skewer-bishop-m1",
 route: "/tactics/m1/bishop-skewer",
 title: "Bishop Skewer - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5710,
 },
 {
 trainerKey: "tactic-skewer-bishop-m2",
 route: "/tactics/m2/bishop-skewer",
 title: "Bishop Skewer - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5720,
 },
 {
 trainerKey: "tactic-skewer-bishop-m3",
 route: "/tactics/m3/bishop-skewer",
 title: "Bishop Skewer - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5730,
 },
 {
 trainerKey: "tactic-skewer-bishop-m4",
 route: "/tactics/m4/bishop-skewer",
 title: "Bishop Skewer - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5740,
 },
 {
 trainerKey: "tactic-skewer-other-m1",
 route: "/tactics/m1/other-skewer",
 title: "Other Skewer - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5750,
 },
 {
 trainerKey: "tactic-skewer-other-m2",
 route: "/tactics/m2/other-skewer",
 title: "Other Skewer - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5760,
 },
 {
 trainerKey: "tactic-skewer-other-m3",
 route: "/tactics/m3/other-skewer",
 title: "Other Skewer - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5770,
 },
 {
 trainerKey: "tactic-skewer-other-m4",
 route: "/tactics/m4/other-skewer",
 title: "Other Skewer - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5780,
 },
 {
 trainerKey: "tactic-decoy-attraction-m1",
 route: "/tactics/m1/decoy-attraction",
 title: "Decoy / Attraction - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5790,
 },
 {
 trainerKey: "tactic-decoy-attraction-m2",
 route: "/tactics/m2/decoy-attraction",
 title: "Decoy / Attraction - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5800,
 },
 {
 trainerKey: "tactic-decoy-attraction-m3",
 route: "/tactics/m3/decoy-attraction",
 title: "Decoy / Attraction - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5810,
 },
 {
 trainerKey: "tactic-decoy-attraction-m4",
 route: "/tactics/m4/decoy-attraction",
 title: "Decoy / Attraction - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5820,
 },
 {
 trainerKey: "tactic-deflection-m1",
 route: "/tactics/m1/deflection",
 title: "Deflection - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5830,
 },
 {
 trainerKey: "tactic-deflection-m2",
 route: "/tactics/m2/deflection",
 title: "Deflection - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5840,
 },
 {
 trainerKey: "tactic-deflection-m3",
 route: "/tactics/m3/deflection",
 title: "Deflection - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5850,
 },
 {
 trainerKey: "tactic-deflection-m4",
 route: "/tactics/m4/deflection",
 title: "Deflection - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5860,
 },
 {
 trainerKey: "tactic-decoy-deflection-combined-m1",
 route: "/tactics/m1/decoy-deflection",
 title: "Decoy + Deflection - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5870,
 },
 {
 trainerKey: "tactic-decoy-deflection-combined-m2",
 route: "/tactics/m2/decoy-deflection",
 title: "Decoy + Deflection - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5880,
 },
 {
 trainerKey: "tactic-decoy-deflection-combined-m3",
 route: "/tactics/m3/decoy-deflection",
 title: "Decoy + Deflection - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5890,
 },
 {
 trainerKey: "tactic-decoy-deflection-combined-m4",
 route: "/tactics/m4/decoy-deflection",
 title: "Decoy + Deflection - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5900,
 },
 {
 trainerKey: "tactic-hanging-piece-m1",
 route: "/tactics/m1/hanging-piece",
 title: "Hanging Piece - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5910,
 },
 {
 trainerKey: "tactic-hanging-piece-m2",
 route: "/tactics/m2/hanging-piece",
 title: "Hanging Piece - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5920,
 },
 {
 trainerKey: "tactic-hanging-piece-m3",
 route: "/tactics/m3/hanging-piece",
 title: "Hanging Piece - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5930,
 },
 {
 trainerKey: "tactic-hanging-piece-m4",
 route: "/tactics/m4/hanging-piece",
 title: "Hanging Piece - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5940,
 },
 {
 trainerKey: "tactic-trapped-piece-m1",
 route: "/tactics/m1/trapped-piece",
 title: "Trapped Piece - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5950,
 },
 {
 trainerKey: "tactic-trapped-piece-m2",
 route: "/tactics/m2/trapped-piece",
 title: "Trapped Piece - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5960,
 },
 {
 trainerKey: "tactic-trapped-piece-m3",
 route: "/tactics/m3/trapped-piece",
 title: "Trapped Piece - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5970,
 },
 {
 trainerKey: "tactic-trapped-piece-m4",
 route: "/tactics/m4/trapped-piece",
 title: "Trapped Piece - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5980,
 },
 {
 trainerKey: "tactic-remove-the-defender-m1",
 route: "/tactics/m1/remove-the-defender",
 title: "Remove the Defender - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 5990,
 },
 {
 trainerKey: "tactic-remove-the-defender-m2",
 route: "/tactics/m2/remove-the-defender",
 title: "Remove the Defender - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6000,
 },
 {
 trainerKey: "tactic-remove-the-defender-m3",
 route: "/tactics/m3/remove-the-defender",
 title: "Remove the Defender - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6010,
 },
 {
 trainerKey: "tactic-remove-the-defender-m4",
 route: "/tactics/m4/remove-the-defender",
 title: "Remove the Defender - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6020,
 },
 {
 trainerKey: "tactic-vulnerable-king-m1",
 route: "/tactics/m1/vulnerable-king",
 title: "Vulnerable / Exposed King - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6030,
 },
 {
 trainerKey: "tactic-vulnerable-king-m3",
 route: "/tactics/m3/vulnerable-king",
 title: "Vulnerable / Exposed King - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6040,
 },
 {
 trainerKey: "tactic-vulnerable-king-m4",
 route: "/tactics/m4/vulnerable-king",
 title: "Vulnerable / Exposed King - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6050,
 },
 {
 trainerKey: "tactic-kingside-attack-m1",
 route: "/tactics/m1/kingside-attack",
 title: "Kingside Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6060,
 },
 {
 trainerKey: "tactic-kingside-attack-m2",
 route: "/tactics/m2/kingside-attack",
 title: "Kingside Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6070,
 },
 {
 trainerKey: "tactic-kingside-attack-m3",
 route: "/tactics/m3/kingside-attack",
 title: "Kingside Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6080,
 },
 {
 trainerKey: "tactic-kingside-attack-m4",
 route: "/tactics/m4/kingside-attack",
 title: "Kingside Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6090,
 },
 {
 trainerKey: "tactic-queenside-attack-m1",
 route: "/tactics/m1/queenside-attack",
 title: "Queenside Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6100,
 },
 {
 trainerKey: "tactic-queenside-attack-m2",
 route: "/tactics/m2/queenside-attack",
 title: "Queenside Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6110,
 },
 {
 trainerKey: "tactic-queenside-attack-m3",
 route: "/tactics/m3/queenside-attack",
 title: "Queenside Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6120,
 },
 {
 trainerKey: "tactic-queenside-attack-m4",
 route: "/tactics/m4/queenside-attack",
 title: "Queenside Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6130,
 },
 {
 trainerKey: "tactic-attacking-f2-f7-m1",
 route: "/tactics/m1/attacking-f2-f7",
 title: "Attacking f2/f7 - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6140,
 },
 {
 trainerKey: "tactic-attacking-f2-f7-m2",
 route: "/tactics/m2/attacking-f2-f7",
 title: "Attacking f2/f7 - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6150,
 },
 {
 trainerKey: "tactic-attacking-f2-f7-m3",
 route: "/tactics/m3/attacking-f2-f7",
 title: "Attacking f2/f7 - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6160,
 },
 {
 trainerKey: "tactic-attacking-f2-f7-m4",
 route: "/tactics/m4/attacking-f2-f7",
 title: "Attacking f2/f7 - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6170,
 },
 {
 trainerKey: "tactic-sacrifice-queen-m1",
 route: "/tactics/m1/queen-sacrifice",
 title: "Queen Sacrifice - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6180,
 },
 {
 trainerKey: "tactic-sacrifice-queen-m2",
 route: "/tactics/m2/queen-sacrifice",
 title: "Queen Sacrifice - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6190,
 },
 {
 trainerKey: "tactic-sacrifice-queen-m3",
 route: "/tactics/m3/queen-sacrifice",
 title: "Queen Sacrifice - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6200,
 },
 {
 trainerKey: "tactic-sacrifice-queen-m4",
 route: "/tactics/m4/queen-sacrifice",
 title: "Queen Sacrifice - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6210,
 },
 {
 trainerKey: "tactic-sacrifice-rook-m1",
 route: "/tactics/m1/rook-sacrifice",
 title: "Rook Sacrifice - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6220,
 },
 {
 trainerKey: "tactic-sacrifice-rook-m2",
 route: "/tactics/m2/rook-sacrifice",
 title: "Rook Sacrifice - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6230,
 },
 {
 trainerKey: "tactic-sacrifice-rook-m3",
 route: "/tactics/m3/rook-sacrifice",
 title: "Rook Sacrifice - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6240,
 },
 {
 trainerKey: "tactic-sacrifice-rook-m4",
 route: "/tactics/m4/rook-sacrifice",
 title: "Rook Sacrifice - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6250,
 },
 {
 trainerKey: "tactic-sacrifice-bishop-m1",
 route: "/tactics/m1/bishop-sacrifice",
 title: "Bishop Sacrifice - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6260,
 },
 {
 trainerKey: "tactic-sacrifice-bishop-m2",
 route: "/tactics/m2/bishop-sacrifice",
 title: "Bishop Sacrifice - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6270,
 },
 {
 trainerKey: "tactic-sacrifice-bishop-m3",
 route: "/tactics/m3/bishop-sacrifice",
 title: "Bishop Sacrifice - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6280,
 },
 {
 trainerKey: "tactic-sacrifice-bishop-m4",
 route: "/tactics/m4/bishop-sacrifice",
 title: "Bishop Sacrifice - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6290,
 },
 {
 trainerKey: "tactic-sacrifice-knight-m1",
 route: "/tactics/m1/knight-sacrifice",
 title: "Knight Sacrifice - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6300,
 },
 {
 trainerKey: "tactic-sacrifice-knight-m2",
 route: "/tactics/m2/knight-sacrifice",
 title: "Knight Sacrifice - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6310,
 },
 {
 trainerKey: "tactic-sacrifice-knight-m3",
 route: "/tactics/m3/knight-sacrifice",
 title: "Knight Sacrifice - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6320,
 },
 {
 trainerKey: "tactic-sacrifice-knight-m4",
 route: "/tactics/m4/knight-sacrifice",
 title: "Knight Sacrifice - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6330,
 },
 {
 trainerKey: "tactic-sacrifice-pawn-m1",
 route: "/tactics/m1/pawn-sacrifice",
 title: "Pawn Sacrifice - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6340,
 },
 {
 trainerKey: "tactic-sacrifice-pawn-m2",
 route: "/tactics/m2/pawn-sacrifice",
 title: "Pawn Sacrifice - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6350,
 },
 {
 trainerKey: "tactic-sacrifice-pawn-m3",
 route: "/tactics/m3/pawn-sacrifice",
 title: "Pawn Sacrifice - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6360,
 },
 {
 trainerKey: "tactic-sacrifice-pawn-m4",
 route: "/tactics/m4/pawn-sacrifice",
 title: "Pawn Sacrifice - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6370,
 },
 {
 trainerKey: "tactic-sacrifice-king-m1",
 route: "/tactics/m1/king-sacrifice",
 title: "King Sacrifice - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6380,
 },
 {
 trainerKey: "tactic-sacrifice-king-m2",
 route: "/tactics/m2/king-sacrifice",
 title: "King Sacrifice - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6390,
 },
 {
 trainerKey: "tactic-sacrifice-king-m3",
 route: "/tactics/m3/king-sacrifice",
 title: "King Sacrifice - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6400,
 },
 {
 trainerKey: "tactic-sacrifice-king-m4",
 route: "/tactics/m4/king-sacrifice",
 title: "King Sacrifice - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6410,
 },
 {
 trainerKey: "tactic-clearance-m1",
 route: "/tactics/m1/clearance",
 title: "Clearance - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6420,
 },
 {
 trainerKey: "tactic-clearance-m2",
 route: "/tactics/m2/clearance",
 title: "Clearance - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6430,
 },
 {
 trainerKey: "tactic-clearance-m3",
 route: "/tactics/m3/clearance",
 title: "Clearance - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6440,
 },
 {
 trainerKey: "tactic-clearance-m4",
 route: "/tactics/m4/clearance",
 title: "Clearance - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6450,
 },
 {
 trainerKey: "tactic-clearance-sacrifice-m1",
 route: "/tactics/m1/clearance-sacrifice",
 title: "Clearance Sacrifice - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6460,
 },
 {
 trainerKey: "tactic-clearance-sacrifice-m2",
 route: "/tactics/m2/clearance-sacrifice",
 title: "Clearance Sacrifice - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6470,
 },
 {
 trainerKey: "tactic-clearance-sacrifice-m3",
 route: "/tactics/m3/clearance-sacrifice",
 title: "Clearance Sacrifice - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6480,
 },
 {
 trainerKey: "tactic-clearance-sacrifice-m4",
 route: "/tactics/m4/clearance-sacrifice",
 title: "Clearance Sacrifice - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6490,
 },
 {
 trainerKey: "tactic-interference-m1",
 route: "/tactics/m1/interference",
 title: "Interference - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6500,
 },
 {
 trainerKey: "tactic-interference-m2",
 route: "/tactics/m2/interference",
 title: "Interference - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6510,
 },
 {
 trainerKey: "tactic-interference-m3",
 route: "/tactics/m3/interference",
 title: "Interference - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6520,
 },
 {
 trainerKey: "tactic-interference-m4",
 route: "/tactics/m4/interference",
 title: "Interference - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6530,
 },
 {
 trainerKey: "tactic-interference-sacrifice-m1",
 route: "/tactics/m1/interference-sacrifice",
 title: "Interference Sacrifice - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6540,
 },
 {
 trainerKey: "tactic-interference-sacrifice-m2",
 route: "/tactics/m2/interference-sacrifice",
 title: "Interference Sacrifice - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6550,
 },
 {
 trainerKey: "tactic-interference-sacrifice-m3",
 route: "/tactics/m3/interference-sacrifice",
 title: "Interference Sacrifice - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6560,
 },
 {
 trainerKey: "tactic-interference-sacrifice-m4",
 route: "/tactics/m4/interference-sacrifice",
 title: "Interference Sacrifice - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6570,
 },
 {
 trainerKey: "tactic-xray-queen-m1",
 route: "/tactics/m1/queen-xray",
 title: "Queen X-Ray Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6580,
 },
 {
 trainerKey: "tactic-xray-queen-m2",
 route: "/tactics/m2/queen-xray",
 title: "Queen X-Ray Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6590,
 },
 {
 trainerKey: "tactic-xray-queen-m3",
 route: "/tactics/m3/queen-xray",
 title: "Queen X-Ray Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6600,
 },
 {
 trainerKey: "tactic-xray-queen-m4",
 route: "/tactics/m4/queen-xray",
 title: "Queen X-Ray Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6610,
 },
 {
 trainerKey: "tactic-xray-rook-m1",
 route: "/tactics/m1/rook-xray",
 title: "Rook X-Ray Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6620,
 },
 {
 trainerKey: "tactic-xray-rook-m2",
 route: "/tactics/m2/rook-xray",
 title: "Rook X-Ray Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6630,
 },
 {
 trainerKey: "tactic-xray-rook-m3",
 route: "/tactics/m3/rook-xray",
 title: "Rook X-Ray Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6640,
 },
 {
 trainerKey: "tactic-xray-rook-m4",
 route: "/tactics/m4/rook-xray",
 title: "Rook X-Ray Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6650,
 },
 {
 trainerKey: "tactic-xray-bishop-m1",
 route: "/tactics/m1/bishop-xray",
 title: "Bishop X-Ray Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6660,
 },
 {
 trainerKey: "tactic-xray-bishop-m2",
 route: "/tactics/m2/bishop-xray",
 title: "Bishop X-Ray Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6670,
 },
 {
 trainerKey: "tactic-xray-bishop-m3",
 route: "/tactics/m3/bishop-xray",
 title: "Bishop X-Ray Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6680,
 },
 {
 trainerKey: "tactic-xray-bishop-m4",
 route: "/tactics/m4/bishop-xray",
 title: "Bishop X-Ray Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6690,
 },
 {
 trainerKey: "tactic-xray-other-m1",
 route: "/tactics/m1/other-xray",
 title: "Other X-Ray Attack - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6700,
 },
 {
 trainerKey: "tactic-xray-other-m2",
 route: "/tactics/m2/other-xray",
 title: "Other X-Ray Attack - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6710,
 },
 {
 trainerKey: "tactic-xray-other-m3",
 route: "/tactics/m3/other-xray",
 title: "Other X-Ray Attack - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6720,
 },
 {
 trainerKey: "tactic-xray-other-m4",
 route: "/tactics/m4/other-xray",
 title: "Other X-Ray Attack - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6730,
 },
 {
 trainerKey: "tactic-promotion-m1",
 route: "/tactics/m1/promotion",
 title: "Promotion - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6740,
 },
 {
 trainerKey: "tactic-promotion-m2",
 route: "/tactics/m2/promotion",
 title: "Promotion - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6750,
 },
 {
 trainerKey: "tactic-promotion-m3",
 route: "/tactics/m3/promotion",
 title: "Promotion - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6760,
 },
 {
 trainerKey: "tactic-promotion-m4",
 route: "/tactics/m4/promotion",
 title: "Promotion - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6770,
 },
 {
 trainerKey: "tactic-underpromotion-m1",
 route: "/tactics/m1/underpromotion",
 title: "Underpromotion - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6780,
 },
 {
 trainerKey: "tactic-underpromotion-m2",
 route: "/tactics/m2/underpromotion",
 title: "Underpromotion - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6790,
 },
 {
 trainerKey: "tactic-underpromotion-m3",
 route: "/tactics/m3/underpromotion",
 title: "Underpromotion - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6800,
 },
 {
 trainerKey: "tactic-underpromotion-m4",
 route: "/tactics/m4/underpromotion",
 title: "Underpromotion - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6810,
 },
 {
 trainerKey: "tactic-underpromotion-knight-m1",
 route: "/tactics/m1/knight-underpromotion",
 title: "Knight Underpromotion - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6820,
 },
 {
 trainerKey: "tactic-underpromotion-knight-m2",
 route: "/tactics/m2/knight-underpromotion",
 title: "Knight Underpromotion - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6830,
 },
 {
 trainerKey: "tactic-underpromotion-knight-m3",
 route: "/tactics/m3/knight-underpromotion",
 title: "Knight Underpromotion - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6840,
 },
 {
 trainerKey: "tactic-underpromotion-knight-m4",
 route: "/tactics/m4/knight-underpromotion",
 title: "Knight Underpromotion - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6850,
 },
 {
 trainerKey: "tactic-en-passant-m1",
 route: "/tactics/m1/en-passant",
 title: "En Passant - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6860,
 },
 {
 trainerKey: "tactic-en-passant-m2",
 route: "/tactics/m2/en-passant",
 title: "En Passant - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6870,
 },
 {
 trainerKey: "tactic-en-passant-m3",
 route: "/tactics/m3/en-passant",
 title: "En Passant - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6880,
 },
 {
 trainerKey: "tactic-en-passant-m4",
 route: "/tactics/m4/en-passant",
 title: "En Passant - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6890,
 },
 {
 trainerKey: "tactic-zugzwang-m1",
 route: "/tactics/m1/zugzwang",
 title: "Zugzwang - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6900,
 },
 {
 trainerKey: "tactic-zugzwang-m2",
 route: "/tactics/m2/zugzwang",
 title: "Zugzwang - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6910,
 },
 {
 trainerKey: "tactic-zugzwang-m3",
 route: "/tactics/m3/zugzwang",
 title: "Zugzwang - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6920,
 },
 {
 trainerKey: "tactic-zugzwang-m4",
 route: "/tactics/m4/zugzwang",
 title: "Zugzwang - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6930,
 },
 {
 trainerKey: "tactic-zwischenzug-m1",
 route: "/tactics/m1/zwischenzug",
 title: "Zwischenzug / Intermezzo - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6940,
 },
 {
 trainerKey: "tactic-zwischenzug-m2",
 route: "/tactics/m2/zwischenzug",
 title: "Zwischenzug / Intermezzo - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6950,
 },
 {
 trainerKey: "tactic-zwischenzug-m3",
 route: "/tactics/m3/zwischenzug",
 title: "Zwischenzug / Intermezzo - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6960,
 },
 {
 trainerKey: "tactic-zwischenzug-m4",
 route: "/tactics/m4/zwischenzug",
 title: "Zwischenzug / Intermezzo - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6970,
 },
 {
 trainerKey: "tactic-mixed-m1",
 route: "/tactics/m1/mixed",
 title: "Mixed - Tactic in 1",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6980,
 },
 {
 trainerKey: "tactic-mixed-m2",
 route: "/tactics/m2/mixed",
 title: "Mixed - Tactic in 2",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 6990,
 },
 {
 trainerKey: "tactic-mixed-m3",
 route: "/tactics/m3/mixed",
 title: "Mixed - Tactic in 3",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 7000,
 },
 {
 trainerKey: "tactic-mixed-m4",
 route: "/tactics/m4/mixed",
 title: "Mixed - Tactic in 4+",
 category: "tactics",
 studyType: "chunk",
 autoEnabled: true,
 sortOrder: 7010,
 },

// =====================
 // BOARD VISION
 // =====================
 {
 trainerKey: "board-vision-basic",
 route: "/board-vision",
 title: "Board Vision",
 category: "board-vision",
 studyType: "vision",
 autoEnabled: true,
 sortOrder: 200,
 },

 // =====================
 // MASTER GAMES
 // =====================
 {
 trainerKey: "master-games-basic",
 route: "/master-games",
 title: "Master Games",
 category: "master-games",
 studyType: "game",
 autoEnabled: true,
 sortOrder: 300,
 },
]

function hasActiveTacticPageConfig(route: string) {
 const match = route.match(/^\/tactics\/(m[1-4])\/([^/]+)$/)
 if (!match) return false

 const configKey = `${match[1]}/${match[2]}` as keyof typeof patternTacticConfigByRoute
 return Boolean(patternTacticConfigByRoute[configKey])
}

/**
 * Auto Training may only select tactic routes backed by the live page-config map.
 * This keeps intentionally hidden/offline collections out of rotation while direct
 * invalid routes continue to use their existing not-found handling.
 */
function isAutoTrainerAvailable(trainer: TrainerCatalogEntry) {
 if (!trainer.autoEnabled) return false
 if (trainer.category !== "tactics") return true
 return hasActiveTacticPageConfig(trainer.route)
}

export const AUTO_TRAINERS = TRAINER_CATALOG
 .filter(isAutoTrainerAvailable)
 .sort((a, b) => a.sortOrder - b.sortOrder)

export const TRAINER_BY_KEY = Object.fromEntries(
 TRAINER_CATALOG.map((trainer) => [trainer.trainerKey, trainer])
) as Record<string, TrainerCatalogEntry>

export function getTrainerByKey(
 trainerKey: string
): TrainerCatalogEntry | undefined {
 return TRAINER_BY_KEY[trainerKey]
}
